
# ARGUE ONE SIDE

Đối với một bài IELTS Writing Task 2, bố cục thường sẽ gồm bốn phần như dưới đây:
Cách viết của mỗi phần sẽ được đề cập lần lượt theo thứ tự.

* The introduction  
* Body paragraph 1  
* Body paragraph 2  
* The conclusion  

Hãy lưu ý đây là bố cục đơn giản và được ưa chuộng cũng như sử dụng nhiều nhất
hiện nay. Ngoài ra một số tác giả cũng có thể chia bố cục làm 5 đoạn trong đó đoạn
thân bài thứ ba có thể là viết thêm một ý kiến nữa hoặc chèn thêm đoạn
Counter-Argument (đây là nội dung khó và chúng ta sẽ không thảo luận ở đây). Về cơ
bản đối mặt với áp lực thời gian khi viết Task 2 đây sẽ là cách lựa chọn tối ưu hơn cho
chúng ta, những người hoặc IELTS và chưa đạt đến trình độ của một người bản xứ.

Bây giờ hãy quan sát ví dụ dưới đây:

Example 1

<p class="formula">
Extreme sports such as sky diving and skiing are very dangerous and should be
banned. To what extent do you agree or disagree with this view?
</p>

Các môn thể thao mạo hiểm ví dụ như nhảy dù và trượt tuyết rất nguy hiểm và nên
bị cấm. Bạn đồng ý hay không đồng ý với quan điểm này?

- sky diving (u) parachuting: nhảy dù
- extreme sport (c) thể thao mạo hiểm
- Một số từ dùng thay cho extreme sports: dangerous sports, high-risk pastimes, high-risk pursuits, action sports, adventure sports.

## Introduction

Đối với dạng này chúng ta có thể áp dụng cách sau để trình bày phần mở bài, bố cục
gồm ba phần chính như sau:

* Background information
* People’s opinion
* Your opinion

Lưu ý là không có quy tắc bắt buộc đối với việc trình bày phần introduction. Miễn là
các bạn đưa ra được vấn đề sẽ thảo luận trong đoạn thân bài thì đều ổn. Tuy nhiên ở
đây mình đưa phần your opinion vào để tránh việc khi các bạn không viết kịp phần
kết bài thì câu trả lời của các bạn cũng đã đưa được ý kiến cá nhân để trả lời câu hỏi
của đề bài và không bị mất nhiều điểm của tiêu chí Task Achievement.

### Background information

Đầu tiên là phần “background information”, ở phần này chúng ta sẽ chỉ đưa một
thông tin chung chung nào đó có liên quan đến phần mở bài của mình. Có khá nhiều
cách để viết phần này, ví dụ trong bài này chúng ta có thể đưa ra một câu thực trạng
hiện nay của những môn thể thao nguy hiểm.

Một lưu ý là câu này không nên nghiêng về hướng nào cả, chỉ đưa ra thông tin nền
để gợi mở vấn đề tranh luận của những câu sau. Chúng ta có thể viết phần background như sau:

In recent years, dangerous sports have become increasingly prevalent in both
the developing and developed world, especially among the younger
generation.

Trong những năm gần đây thể thao mạo hiểm đang trở nên ngày càng được
yêu thích ở rất nhiều nơi trên thế giời, đặc biệt là đối với giới trẻ.

- increasingly (adv) ngày càng
- prevalent = common (adj) phổ biến
- the developed world = developed countries (n) các nước phát triển
- the developing world = developing countries (n) các nước đang phát triển
- the younger generation = the youth (n) giới trẻ

Ngoài cách trên, một mẹo khá hay để bắt đầu phần background information này đó
là nói về việc ngày nay mọi người có những quan điểm trái chiều về vấn đề đang
được thảo luận. Nếu áp dụng cách này chúng ta thường có thể bắt đầu viết phần
background nhanh chóng bằng các mẫu câu sau:

<ul class="formula">
<li> Today, there are plenty of opposing opinions about whether S + V   </li>
<li> Recently, there has been a lot of debate as to whether S + V   </li>
<li> There is a growing concern in these years that S + V   </li>
<li> In recent years, there has been a growing trend towards + N/$V_ing$   </li>
</ul>

<ul class="formula">
<li>Nowadays people hold different opinions about whether S + V  </li>
<li>Individuals take different views towards whether S + V  </li>
<li>General public takes different points of view towards + N/$V_ing$  </li>
</ul>

<ul class="formula">
<li>A question central to the current public debate is whether S + V  </li>
<li>An issue people are openly debating is whether S + V  </li>
<li>Opinions divide concerning whether S + V  </li>
</ul>

<ul class="formula">
<li>It is an controversial subject whether S + V  </li>
<li>It is a subject of debate whether S + V  </li>
</ul>

<ul class="formula">
<li>N/$V_ing$ is one of the greatest social problems of our time.  </li>
<li>N/$V_ing$ has long been an issue of concern to the public and to governments.  </li>
</ul>

Lưu ý chúng ta thường có thể dùng mệnh đề danh từ whether với nghĩa là “có hoặc không” trong các công thức trên. Áp dụng cách này vào ví dụ trên chúng ta có thể viết được một phần background mà
không cần phải suy nghĩ nhiều như sau:

<p class="comment">
Nowadays people hold different opinions about whether high-risk activities
such as parachuting and rock climbing should be prohibited or not.
</p>

Ngày nay mọi người có quan điểm khác nhau về việc những hoạt động nguy
hiểm như nhảy dù và trượt tuyết có nên bị cấm hay không.

Ví dụ khác:

<p class="comment">
Nowadays people hold opposing opinions about whether governments
should prevent cars from city centers or not.
</p>

Ngày nay nhiều người giữ quan điểm khác nhau về việc chính phủ có nên ngăn
xe hơi vào các trung tâm thành phố hay không.

<p class="comment">
Today there are plenty of opposing opinions about whether children should
be given homework by their teachers or not.
</p>

Ngày nay có khá nhiều những ý kiến trái chiều về việc trẻ em có nên được giao
bài tập về nhà bởi giáo viên hay không.

<p class="comment">
It is a subject of debate whether parents should be held responsible for their
underage children’s law-offending acts.
</p>

Cha mẹ có nên chịu trách nhiệm cho những hành vi vi phạm pháp luật của con
cái chưa đủ tuổi trưởng thành hay không là một vấn đề gây tranh luận.

Lưu ý là dù chọn cách viết nào thì các bạn cũng không nên copy hoàn toàn đề bài.
Hãy vận dụng kiến thức về từ đồng nghĩa để thay thế các từ được cho trong đề bài,
đồng thời các bạn cũng có thể đổi cấu trúc ngữ pháp để tránh bị lặp lại cấu trúc.

Ví dụ như đề bài của chúng ta là:

<p class="comment">
Extreme sports such as sky diving and skiing are very dangerous and should be
banned.
</p>

Chúng ta có thể viết lại như:

<p class="comment">
Today, there are plenty of opposing opinions about whether or not high-risk activities such as parachuting and rock climbing should be prohibited.  
</p>

<p class="comment">
Individuals take different views towards whether it is justified to prohibit adventure sports such as parachuting and rock climbing.  
</p>

<p class="comment">
A question central to the current public debate is whether or not banning risky activities such as parachuting and rock climbing is justified.  
</p>

### People’s opinion

Sau khi đã viết một background information chúng ta có thể thêm phần ý kiến của
những người khác.

Lưu ý đây chỉ là phần cố tình được đưa vào để dẫn đến ý kiến của bạn. Phần này sẽ
giúp phần introduction của bạn dài hơn khi bạn không có khả năng viết một câu dài.
Đối với các bạn có khả năng viết câu background đủ dài thì hoàn toàn có thể bỏ qua
phần này mà đi trực tiếp vào phần sau.

Trong phần ý kiến của mọi người này, chúng ta hãy chọn một
hướng“agree/positive/should” hoặc “disagree/negative/should not” bất kì.
Thông thường để viết câu này các bạn có thể bắt đầu câu bằng những cụm sau đây:

<ul class="formula">
<li>There is a perception that S + V  </li>
<li>The idea that S + V has become widely accepted.  </li>
</ul>

<ul class="formula">
<li>Many people agree that S + V               </li>
<li>Many people contend that S + V             </li>
<li>Many people claim that S + V  </li>
<li>Some people hold the view that S + V  </li>
<li>Many people maintain that S + V  </li>
<li>Some people take the position that S + V  </li>
<li>One has reasons to believe that S + V  </li>
<li>Some people subscribe to a view that S + V  </li>
</ul>

<ul class="formula">
<li>Opponents argue that S + V  </li>
<li>Critics claim that S + V  </li>
<li>Proponents believe that S + V  </li>
<li>Those who oppose N/$V_ing$ often argue that S + V  </li>
</ul>

<ul class="formula">
<li>It is often said that S + V                 </li>
<li>it is often claimed that S + V              </li>
<li>It is often believed that S + V             </li>
<li>It is often argued that S + V               </li>
<li>It is suggested that S + V      </li>
</ul>

Bên cạnh đó chúng ta cũng thường cần dùng nhiều từ chỉ quan điểm thay phiên cho
nhau ví du như:

* view  
* opinion  
* point of view  
* viewpoint (quan điểm)  
* statement (lời tuyên bố, phát biểu)  
* assertion (lời khẳng định)  
* contention  
* perception  
* notion


Ví dụ như đối với đề bài này ý kiến của mọi người có thể được viết như sau:

<p class="comment">
It is normally argued that the prohibition of such hazardous pursuits, which
result in a great number of fatalities per year, is completely justified.
</p>

Mọi người thường cho rằng cấm những hoạt động này, cái gây ra rất nhiều cái
chết cho mọi người mỗi năm, là hoàn toàn hợp lý

- prohibition (u) sự cấm
- high-risk = risky = dangerous = hazardous (adj) nguy hiểm
- result in = lead to: dẫn đến
- death = fatality (c) cái chết
- justified (adj) hợp lý

### Your opinion

Phần này luôn là phần quan trọng nhất của introduction, vì phần này chúng ta sẽ trả
lời câu hỏi của đề bài. Câu trả lời của chúng ta trong phần này sẽ giúp người đọc hiểu
được bố cục phần thân bài của chúng ta như thế nào.

Như đã nói sau khi đưa ra ý kiến của mọi người theo một hướng tự chọn nào đó. Bây
giờ chúng ta sẽ chọn hướng của mình.

Cách 1: Nếu bạn đồng tình với ý kiến của mọi người, hãy sử dụng:

<ul class="formula">
<li>I completely agree with this point of view.  </li>
<li>In my opinion, this point of view is well-founded.</li>
<li>As far as I am concerned, this point of view is well-grounded.</li>
<li>From my own experience, this is a good idea.</li>
<li>As far as I know, this is a good idea.</li>
<li>To the best of my knowledge, this is a good idea.</li>
</ul>

- completely (adv) hoàn toàn
- disagree (i) không đồng ý
- well-founded = well-grounded = justified(adj) có sơ sở

Cách 2: Nếu bạn không đồng tình với ý kiến của mọi người.

<ul class="formula">
<li>I completely disagree with this point of view.</li>
<li>In my opinion, this point of view is unfounded.</li>
<li>As far as I am concerned, this point of view is unfounded.</li>
<li>From my own experience, this is not a good idea.</li>
<li>As far as I know, this is not a good idea.</li>
<li>To the best of my knowledge, this is not a good idea.</li>
<li>I reject this notion, believing that S + V  </li>
<li>I take the opposite position, believing that S + V  </li>
<li>As opposed to this point of view, I believe that S + V  </li>
</ul>

- unfounded = unsupported = ungrounded = unjustified (adj) không có căn cứ

Một số câu trên hơi có vẻ hơi ngắn, như vậy để dài thêm chúng ta có thể chèn thêm
trong đa số các câu trên bằng:
“and here/these are my reasons” hoặc “and my reasons are as follows” ở đằng sau.
Phần này được thêm vào để làm dài phần mở bài, cũng như thông báo cho người
đọc những lý lẽ của mình sẽ nằm ở hai đoạn thân bài.

Chúng ta sẽ có phần ý kiến cá nhân đầy đủ như sau:

<ul class="formula">
<li>I completely agree with this point of view, and here/these are my reasons.  </li>
<li>I completely disagree with this point of view, and my reasons are as follows.  </li>
<li>I reject this notion, believing that adventure sports bring more benefits to society than disadvantages they create.</li>
</ul>


Ngoài ra các bạn có thể dùng các từ như “However, in contrast” để thể hiện ý kiến
trái ngược với people’s opinion. Hoặc dùng “similarly, too, also” nếu ý kiến của
chúng ta tương đồng với “people’s opinion”.

Ví dụ chúng ta có thể viết ý kiến của mình như sau:

<p class="comment">
Similarly, I believe that adventure sports are hazardous and it is advisable
to ban them.  
</p>

<p class="comment">
I am also supportive of this point of view, and here/these are my reasons.
</p>

<p class="comment">
However, I completely disagree with this point of view, and my reasons are
as follows.  
</p>

<p class="comment">
In contrast, I take the opposite position, believing that adventure sports
bring more benefits to society than disadvantages they create.  
</p>

<p class="comment">
However, I reject this notion, believing that adventure sports bring more
benefits to society than disadvantages they create.
</p>

Ở đây nói riêng và trong toàn bộ bài essay nói chung chúng ta sẽ dùng khá nhiều cụm
từ kiểu “I believe that”. Có một số cách viết khác như sau:

<ul class="formula">
<li>I personally believe that S + V  </li>
<li>I am supportive of the argument that S + V  </li>
<li>I firmly believe that S + V  </li>
<li>I side with those who believe that S + V  </li>
<li>It is my opinion/view that S + V  </li>
<li>In my opinion/view, S + V  </li>
<li>I hold the view that S + V  </li>
<li>From my perspective, S + V  </li>
<li>I claim that S + V  </li>
<li>From my point of view, S + V  </li>
<li>I argue that S + V  </li>
<li>As far as I am concerned, S + V  </li>
<li>I affirm that S + V  </li>
<li>To the best of my knowledge, S + V  </li>
<li>I contend that S + V  </li>
<li>From my own experience, S + V  </li>
<li>I am of the opinion that S + V  </li>
</ul>

Ghép các thông tin của cả ba phần trên lại chúng ta có một phần introduction đầy đủ như sau:

<p class="comment">
In recent years, dangerous sports have become increasingly prevalent in both
the developing and developed world, especially among the younger
generation. It is argued that such high-risk pursuits as parachuting and rock
climbing, which result in a great number of fatalities every year, should be
prohibited. However, I completely disagree with this viewpoint and here are
my reasons.
</p>

Hoặc:

<p class="comment">
Nowadays people hold different opinions about whether high-risk activities
such as parachuting and rock climbing should be prohibited or not. It is
claimed that the banning of such activities, which result in a great number of
fatalities every year, is a good idea. Similarly, I believe that adventure sports
are hazardous and it is advisable to prohibit them.
</p>

## Body

Sau khi hoàn thành phần mở bài chúng ta sẽ chuyển qua phần thân bài. Thân bài
trong bài viết IELTS Writing Task 2 thường được chia ra làm hai đoạn Body 1 và Body
2 như đã nói ở phần đầu.

### Body Paragraph 1

Bố cục thường dùng cho một đoạn thân bài bao gồm:

* Topic sentence
* Supporting sentence
* Example/More explanation
* Concluding thought

#### Topic sentence

Đối với dạng này chúng ta sẽ có hai đoạn body và mỗi câu topic của một body sẽ đưa
ta một lý do chính để bảo vệ quan điểm của chúng ta ở phần mở bài. Như vậy trong
câu topic của đoạn thân bài thứ nhất chúng ta thường xuyên có thể bắt đầu bằng các
cụm:

<ul class="formula">
<li>The first reason is that S + V  </li>
<li>One reason is that S + V  </li>
<li>One reason for/against N/$V_ing$ is that S + V  </li>
<li>Firstly, S + V  </li>
<li>To begin with, S + V  </li>
<li>First of all, S + V  </li>
<li>For a start, S + V  </li>
<li>The first reason to support/oppose it is that S + V  </li>
<li>The first reason to support the above contention is that S + V  </li>
<li>The first point/fact to note is that S + V  </li>
<li>A strong argument for/against N/$V_ing$ is that  </li>
<li>One of the main objections to X is that S + V  </li>
<li>The first justification for X is that S + V  </li>
<li>One of the most significant benefits obtained from X is that S + V  </li>
<li>It is important to recognize that S + V  </li>
<li>It should be first noted that S + V  </li>
<li>People should first recognize that S + V  </li>
</ul>

- justification (c) a good reason/explanation

Câu đầu tiên là câu topic của đoạn. Câu này là câu quan trọng nhất vì sẽ là câu chủ đề
của đoạn. Tất cả các câu sau sẽ đều chỉ để giải thích và làm rõ câu luận điểm của
mình trong câu này.

Hãy đọc thử câu topic sentence sau:

<p class="comment">
The first reason is that in fact action sports are not as hazardous as people
often imagine they are.
</p>

Lý do đầu tiên đó là thực tế những môn thể thao mạo hiểm không nguy hiểm
như mọi người thường nghĩ.

- actually = in fact (adv) thực ra, thực tế là
- cấu trúc so sánh bằng: as + adj/adv + as (ví dụ she is not as tall as I am)

#### Supporting sentence

Sau khi đưa ra luận điểm chính là các môn thể thao này thực ra không nguy hiểm
như mọi người nghĩ. Bây giờ chúng ta cần viết Supporting sentence để giải thích
cho luận điểm này. Hoặc nói cách khác là giải thích tại sao chúng không nguy hiểm
như mọi người nghĩ.

Có khá nhiều cách để viết Supporting sentence, miễn là nó bổ trợ cho câu topic
sentence thì đều đúng.

Tuy nhiên có một số cách các bạn có thể dùng khi viết đến câu này.

Cách 1: Hãy nghĩ về lý do “why” tại sao câu topic của chúng ta lại đúng.  
Cách 2: Các bạn có thể phát triển tiếp và đưa ra những kết quả tích cực nếu chúng ta
đang bảo vệ hướng có lợi và đưa ra những khó khăn, bất lợi, hậu quả khi chúng ta
đang đi theo hướng gây hại.

Nếu các bạn lựa chọn hướng giải thích như Cách 2 và dẫn đến kết luận.
Các bạn thường cần dùng các từ và cụm từ để nói về kết quả. Các bạn có thể sử
dụng:

<ul class="formula">
<li>So,</li>
<li>Thus,</li>
<li>Therefore,</li>
<li>As a result,</li>
<li>As a consequence,</li>
</ul>

<ul class="formula">
<li>Consequently,</li>
<li>Hence,</li>
<li>Accordingly,</li>
<li>For this reason,</li>
</ul>

Quan sát lại câu topic:

<p class="comment">
The first reason is that in fact action sports are not as hazardous as people
imagine.
</p>

Lý do đầu tiên đó là thực tế những môn thể thao mạo hiểm không nguy hiểm
như mọi người nghĩ.

Chúng ta có thể dùng cách thứ nhất để trả lời cho câu hỏi tại sao câu topic của chúng ta lại đúng như sau:

<p class="comment">
These days, thanks to the scientific and technological breakthroughs, the
degree of risk related to such activities is minimised.
</p>

Ngày nay nhờ vào những bước tiến về khoa học và công nghệ, mức độ rủi ro
liên quan đến những hoạt động này được giảm tới mức tối thiểu.

- thanks to (pre) nhờ vào
- breakthrough (c) bước tiến
- dùng “such” như “this/these” để đề cậplại danh từ phía trước
- minimize (t) giảm tới mức tối thiểu

Đối với câu support này người đọc đã hiểu chúng đang muốn nói đến việc khoa học
và công nghệ đã giúp cho những môn thể thao này không còn nguy hiểm như mọi
người nghĩ. Điều này đã giúp làm rõ ý cho câu topic của chúng ta.

Hãy quan sát thêm một số ví dụ khác để nắm được các cách giúp chúng ta viết phần
support:

##### Examples

###### Examples 1

<p class="comment">
The first reason is that extreme sports enable people to reduce the pressure that they have to cope with at work.
In this age and day people tend to devote most of their time during the week in the workplace and only have days off on the weekend. So, they usually seek recreational activities which could help forget work-related tension, and dangerous sports are among such pursuits.
</p>

###### Examples 2

<p class="comment">
The first reason why I support space missions is that they allow detailed monitoring of the earth. This calculation provides priceless information on the environment in which we live.
Thanks to these data, scientists can produce statistics on the melting of polar ice, rising sea levels and pollution. These figures could raise human awareness of the necessity of curbing practices such as indiscriminate littering or excessive use of cars.
</p>

###### Examples 3

<p class="comment">
The first reason is that users’ obsession with social media consumes a great deal of their time every day for aimless surfing. These heavy users generally lead a sedentary lifestyle and have higher risks of developing several chronic illnesses such as heart disease, diabetes and obesity. 
</p>

#### Example/More explanation

Đa số các bài chúng ta đều có thể lấy ví dụ cụ thể để củng cố thêm cho phần
Supporting sentence.
Ở phần này chúng ta có thể nói cụ thể về một quốc gia, một nhóm tuổi, một lĩnh vực
nào đó. Đây có thể là các thông tin chúng ta đọc ở đâu đó. Hoặc đôi khi chúng ta
cũng có thể lấy ví dụ cá nhân về bản thân mình, ở khu vực mình sinh sống.

Lưu ý không phải lúc nào ý thứ ba này cũng cần viết về một “example” cụ thể. Đôi khi
việc đưa ra một ví dụ là khó thì chúng ta có thể tiếp tục lập luận và giải thích thêm
cho Supporting sentence ở ý thứ ba này. Điều này các bạn sẽ thấy khá nhiều trong
các bài viết task 2.

Để đưa ra ví dụ chúng ta có nhiều cách, nhưng cách thông dụng thường là dùng "for example" hoặc "for instance”. Hoặc chúng ta có thể dùng các cấu trúc như “X can be taken/cited as a typical example” như dưới đây:

<ul class="formula">
<li>For example,  </li>
<li>For instance,  </li>
<li>X can be taken/cited as a typical example.  </li>
<li>A typical/telling example (to support this) is that S + V  </li>
<li>A case in point is that S + V  </li>
</ul>

Trong ví dụ này chúng ta đơn giản có thể lấy ví dụ về các môn thể thao cụ thể.
Các bạn có thể áp dụng để viết phần ví dụ theo những cách khác nhau như sau:

<p class="comment">
For example, participants in sports such as parachuting, motor racing or scuba
diving are always fitted with state-of-the-art equipment like protective
clothing or underwater breathing apparatus.
</p>

Ví dụ, những người tham gia những môn thể thao như nhảy dù, đua xe hay lặn
với bình dưỡng khí luôn được trang bị với thiết bị hiện đại như quần áo bảo
hộ hoặc thiết bị thở dưới nước.

- participant (c) người tham gia
- parachuting (u) môn nhảy dù
- scuba diving (u) môn lặn bằng bình dưỡng khí 
- be fitted with = be equipped with: được trang bị với cái gì đó
- state-of-the-art (adj) hiện đại 
- protective clothing (u) quần áo bảo hộ
- underwater breathing apparatus (c/u) thiết bị thở dưới nước

Hoặc chúng ta có thể viết như sau:

<p class="comment">
The sports such as parachuting, motor racing, or scuba diving can be taken as
a typical example. Participants in these sports are always fitted with
state-of-the-art equipment like protective clothing or underwater breathing
apparatus.
</p>

#### Concluding thought

Sau khi đã hoàn thành phần ví dụ thì cơ bản chúng ta đã hoàn thành xong đoạn thân
bài của mình với đủ ba ý quan trọng nhất. Khi viết câu kết cho đoạn các bạn cần
khẳng định lại đó là dựa vào tất cả những lập luận và dẫn chứng đã đưa ra chúng có
quan hệ gì với luận điểm chính của bạn.

Ví dụ như trong trường hợp này chúng ta có thể viết một câu kết đoạn như sau:

<p class="comment">
This shows that the risk of physical injuries for both amateur and professional
athletes undertaking extreme sports is often kept to a minimum and it is
ungrounded to prohibit them.
</p>


Điều này cho thấy là nguy cơ chấn thương cho cả vận động viên nghiệp dư và
chuyên nghiệp tham gia vào những môn thể thao mạo hiểm thường được
giảm tới mức tối thiểu và cấm chúng là không hợp lý.


- athlete (c) vận động viên                     
- amateur (c/adj) người nghiệp dư, nghiệp dư

Dưới đây là một số cách bắt đầu câu kết đoạn:

<ul class="formula">
<li>It means that S+ V  </li>
<li>From this we can conclude that S+ V  </li>
<li>It is therefore evident that S+ V  </li>
<li>This shows that S + V  </li>
<li>This reflects the fact that S+ V  </li>
<li>This is a reflection of the fact that S+ V  </li>
<li>As a consequence, S+ V  </li>
<li>All this evidence demonstrates that S + V  </li>
</ul>

Bây giờ chúng ta hãy quan sát một đoạn thân bài sau khi hoàn tất:

<p class="comment">
**(Topic sentence)**  
The first reason is that in fact action sports are not as hazardous as people imagine.   
**(Supporting sentence)**  
These days, thanks to
the scientific and technological breakthroughs, the degree of risk related to such activities is minimised.  
**(Example)**  
For example, participants in sports such as parachuting, motor racing, or scuba diving are always fitted with state-of-the-art equipment like protective clothing or underwater breathing apparatus.  
**(Concluding thought)**  
This shows that the risk of physical injuries for both amateur and professional athletes undertaking extreme sports is often kept to a minimum and it is ungrounded to prohibit them.
</p>

### Body Paragraph 2

Phần body paragraph 2 hoàn toàn tương tự như cách lập luận của phần body 1. Chỉ
có khác biệt ở câu mở đầu bởi vì đây là lý do thứ hai chúng ta đưa ra nên các bạn sẽ
bắt đầu bằng:

<ul class="formula">
<li>*Another reason is that S + V     </li>
<li>*A further reason is that S + V              </li>
<li>*The second reason is that S + V  </li>
</ul>

<ul class="formula">
<li>Another satisfactory explanation is that S + V  </li>
<li>Another point to support N/$V_ing$ is that S + V  </li>
<li>Another reason for/against N/$V_ing$ is that S + V  </li>
</ul>

<ul class="formula">
<li>Another problem is that S + V  </li>
<li>Another fact to note is that S + V        </li>
<li>Another benefit obtained from N/$V_ing$ is that S + V  </li>
<li>Another justification for N/$V_ing$ is that S + V  </li>
</ul>

<ul class="formula">
<li>People should meanwhile recognize the fact that S + V  </li>
</ul>

<ul class="formula">
<li>Secondly, S + V                              </li>
<li>Meanwhile, S + V                          </li>
</ul>

Ví dụ áp dụng:

<p class="comment">
The second reason is that such pursuits generate income for enterprises, and so
provide employment to many people involved such as athletes, guides, instructors,
etc.
</p>

<p class="comment">
Another reason against prohibiting adventure sports is that such pursuits generate
income for enterprises, and so provide employment to many people involved such as
athletes, guides, instructors, etc.
</p>

Ngoài ra nếu các bạn bắt đầu bằng các cấu trúc có dấu (*) chúng ta có thể dùng
mệnh đề why phía sau reason, mục đích chỉ để lặp lại ý kiến của mình và kéo dài câu
như sau:

<ul class="formula">
<li>The second reason [why S + V] is that S + V</li>
</ul>

Ví dụ trong trường hợp này: 

<p class="comment">
The second reason [why governments should not ban adventure sports] is that such pursuits generate income for enterprises,
and so provide employment to many people involved such as athletes, guides,
instructors, etc.
</p>

Lý do thứ hai chính phủ không nên cấm các môn thể thao này đó là những
hoạt động tiêu khiển này tạo ra thu nhập cho nhiều doanh nghiệp và vì vậy
mang lại việc làm cho nhiều người liên quan như là vận động viên, hướng dẫn
viên, huấn luyện viên, vân vân.

- income = revenue (u/c) thu nhập, doanh thu
- generate = produce = create (t) tạo ra
- employment = work (u) việc làm
- guide (c) hướng dẫn viên
- instructor (c) huấn luyện viên
- etc. = and so on = and so forth: vân vân

Chúng ta có thể viết câu trong mệnh đề why theo nhiều cách miễn là nó thể hiện
được ý kiến giống trong phần mở bài của chúng ta.

Ví dụ mệnh đề why trong ví dụ này có thể được viết theo một số cách như:

<ul class="formula">
<li>The second reason [why governments should not ban these sports] is that S + V  </li>
<li>The second reason [why banning these sports is unjustified ] is that S + V  </li>
<li>The second reason [why I do not agree with the prohibition of these sports] is that S + V </li>
</ul>

Tuy nhiên lưu ý là trong các cấu trúc trên phần phía sau “that” mới quan trọng vì nó
thể hiện nội dung của câu topic của chúng ta. Đây mới là nội dung chính, còn lại chỉ là
cái cách để chúng ta bắt đầu cũng như kéo dài câu.

Ngoài ra chúng ta không nên dùng mệnh đề why này trong câu topic của đoạn thân
bài đầu tiên vì nó thường sẽ làm cho câu của chúng ta lặp lại nội dung của phần mở
bài. Hai phần quá giống nhau để gần nhau thường làm cho bài viết bị mắc lỗi lặp lại.

Các phần tiếp theo chúng ta chỉ cần trình bày giống đoạn thứ nhất:

<p class="comment">
**(Supporting sentence)**  
In many parts of the world, revenue from adventure
activities contributes greatly to the gross domestic product.  
**(Example)**  
Nepal
can be cited as a typical example since people living around the Himalayas are
heavily dependent on mountaineers. Dangerous mountain climbing has
enabled this area to thrive over the past few decades.  
**(Concluding thought)**  
As
a consequence, the prohibition of these activities can result in fierce
opposition and has a profound impact on economic prosperity of a large
number of countries.
</p>

Ở nhiều khu vực trên thế giới, thu nhập từ các hoạt động thể thao mạo hiểm
đóng góp rất nhiều vào GDP. Nepal có thể được lấy làm một ví dụ điển hình vì
cuộc sống của người dân sống quanh dãy núi Himalayas phụ thuộc rất lớn vào
những người leo núi. Hoạt động leo núi mạo hiểm giúp kinh tế nơi đây trở nên
thịnh vượng trong vài thập kỷ qua. Chính vì vậy cấm những môn thể thao này
có thể dẫn đến sự phản đối và ảnh hưởng tiêu cực đến sự thịnh vượng kinh tế
của nhiều quốc gia.

- revenue (u) doanh thu
- contribute (to) (i) make a contribution to: đóng
góp vào
- gross domestic product = GDP (n) tổng thu nhập quốc nội. - since = because = as (conj) bởi vì - depend heavily on (i) phụ thuộc chính vào
- climber = mountaineer (c) người leo núi - enable sb to do sth: giúp ai đó có thể làm gì đó
- thrive = flourish = prosper (i) thịnh vượng, phát đạt
- prohibition (u) sự cấm
- lead to = result in (phrase) dẫn đến
- fierce (adj) mãnh liệt, dữ dội - opposition = objection = resistance (u) sự phản đối, sự kháng cự
- profound (adj) sâu sắc
- have an impact on = have an effect on =have(an) influence on sth: tác động hoặc ảnhhưởnglên cái gì đó
- prosperity (u) sự thịnh vượng

### Remarks

Có nhiều thắc mắc về việc chúng ta có phải lúc nào cũng cần viết theo bố cục:

* Topic sentence
* Supporting sentence
* Example/More explanation
* Concluding thought

Câu trả lời là không bởi vì trong nhiều trường hợp chỉ phát triển dựa vào một ý sẽ
khá khó. Vì vậy chúng ta có thể viết cả hai luận điểm song song với nhau cùng về một
hướng. (Đây cũng là một cách được nhiều tác giả ưa chuộng, các bạn có thể đọc
được cách sử dụng này ở hầu hết các bài essay mẫu).

Lưu ý là cách trình bày kiểu này có thể áp dụng cho bất cứ dạng nào trong IELTS
Writing Task 2 chứ không phải chỉ riêng dạng này.

Ngoài ra chú ý khi viết theo cách này các bạn vẫn phải cố gắng giải thích hoặc lấy ví
dụ để làm rõ quan điểm của mình. Tránh việc chỉ đưa ra một thông tin chưa được
phát triển đầy đủ sẽ bị trừ điểm trong tiêu chí Coherence & Cohesion.

Cấu trúc của một đoạn thân bài trình bày kiểu này có thể được viết như sau:

* Topic sentence
* Supporting sentence 1
* Example 1/More explanation 1
* Supporting sentence 2
* Example 2/More explanation 2
* Concluding thought

Những lưu ý khi sử dụng cách này:

Câu topic sẽ chưa cần phải đi vào cụ thể mà chỉ cần thông báo là **“There are various
reasons why...”**.

Ở đầu câu Supporting sentence thứ nhất chúng ta có thể dùng 

* firstly
* to begin with
* to start with
* for a start 

hoặc sử dụng các cụm để bắt đầu câu topic sentence đầu tiên như đã hướng dẫn.

Để bắt đầu câu Supporting sentence thứ hai chúng ta cần dùng các từ:

* moreover
* furthermore
* additionally
* besides
* what’s more
* similarly
* likewise

Trong structure như trên phần topic sentence thực chất không quan trọng và chúng
ta có thể bỏ đi, và bắt đầu câu với 

* firstly 
* to begin with

Ngoài ra lưu ý kiểu trình bày như thế này sẽ phù hợp hơn khi các bạn thảo luận về cả
hai hướng vì nếu trình bày theo một hường rất dễ dẫn đến việc thiếu ý tưởng cho
đoạn thứ hai. Bởi vì riêng đoạn thứ nhất mà trình bày như trên chúng ta đã sử dụng
đến hai ý chính để làm luận điểm cho hướng chúng ta chọn rồi. Để nghĩ thêm một ý
tưởng khác cùng về hướng này cho đoạn sau sẽ rất khó khăn.

#### Examples

Dưới đây là một số ví dụ về các cách khác nhau để trình bày một đoạn thân bài:

Example 1

<p class="comment">
**(Topic sentence)**  
There are various reasons why teaching schoolchildren other countries’ literature and history is not a good idea.   
**(Supporting sentence 1)**  
Firstly,
the study of global events and foreign novels could cause unnecessary difficulty and
confusion for school pupils.  
**(Example 1)**  
I do not see the point in presenting Russian
or Chinese history to a British child who has not yet studied the history of his or her
own country in detail. Surely the child would be more able to comprehend historical
events that took place in London than those that happened in Moscow or Beijing.  
**(Supporting sentence 2)**  
Similarly, any exposure to international literature is likely
to require the teaching of a foreign language or the use of translations.  
**(More explanation 2)**  
Young people at primary or secondary school age are simply not
ready for such complications.  
**(Concluding thought)**  
This shows that schools should
lay emphasis on national literature and historical event instead of international
subjects of this kind.
</p>

Example 2

<p class="comment">
**(Topic sentence)**  
There are various reasons why it might be considered beneficial to allow people to be paid extremely high salaries.  
**(Supporting sentence 1)**  
For a start, if companies offer excellent pay packages, they can attract the most talented people in their fields to work for them.  
**(Example 1)**  
For example, technology companies like Google are able to employ the best programmers because of the huge sums that they are willing to pay.  
**(Supporting sentence 2)**  
Furthermore, these well-paid employees are likely to be highly motivated to work hard and therefore drive their businesses successfully.  
**(More explanation 2)**  
In theory, this should result in a thriving economy and increased tax revenues. 
**(Concluding thought)**  
This means that paying high salaries benefits everyone.
</p>

Example 3

<p class="comment">
**(Topic sentence)**  
Another reason why governments should not ban cars is that it would be generally unpopular.  
**(Supporting sentence)**  
There are many vehicles on the roads, and most people like them very much. Society has become heavily dependent on taxis, trucks, and other forms of motorised transport, whose numbers will probably rise every year, leaving little choice apart from acceptance.  
**(Example)**  
My colleagues, for example, often complain about the inadequacy of public transport in a city as large in area as Melbourne and how cars are needed for true convenience.  
**(Concluding thought)**  
Attempts to restrict their usage would thus raise too many objections to be politically acceptant.
</p>

Việc lựa chọn cách nào để trình bày đoạn thân bài sẽ tùy vào đề bài cụ thể và việc
chúng ta có đủ ý để phát triển một câu topic thành cả đoạn hay không, hoặc là có
một ý thứ hai song song song. Miễn là chúng ta cần viết thêm tối thiểu một hoặc hai
câu câu để giải thích được rõ ràng ý mình đưa ra thì mới đáp ứng được yêu cầu của
đề bài.

Trong quyển sách này chúng ta sẽ chủ yếu đi theo hướng phát triển các ý từ Topic
sentence -> Supporting sentence -> Example -> Concluding thought. Bởi vì cách
này sẽ đảm bảo các ý của chúng ta được support, liên kết và phát triển đầy đủ hơn.

Tuy nhiên cách thứ hai cũng có thể áp dụng cho những dạng đặc biệt ở phần sau.

Điểm tiếp theo chúng ta cần lưu ý đó là không phải lúc nào các phần Supporting
sentence(s) hoặc Example cũng là một câu. Đối với nhiều bạn việc chỉ viết bốn câu
cho bốn phần và đạt xấp xỉ 100 từ là điều không hề dễ dàng. Chính vì vậy một phần
nào đó có hai hoặc đôi khi 3 câu là hoàn toàn bình thường miễn là chúng ta đã chốt
được ý của mình thì đều chấp nhận được.

Hãy xem ví dụ dưới đây:

<p class="comment">
**(Topic sentence)**   
Gaming can be highly addictive because users are constantly given scores, new targets and frequent rewards to keep them playing.  
**(Supporting sentence)**  
Many children now spend hours each day trying to progress through the levels of a game or to get a higher score than their friends.  
**(Example)**  
This type of addiction can have effects ranging from lack of sleep to problems at school, when homework is sacrificed for a few more hours on the computer or console. The rise in obesity in recent years has also been linked in part to the sedentary lifestyle and lack of exercise that often accompany gaming addiction.  
**(Concluding thought)**  
This reflects the detrimental implications video games have for players.
</p>


Trong đoạn thân bài này phần Example của chúng ta có đến hai câu để phát triển ý
cho Supporting sentence.

Một điểm khác đã đề cập ở các phần trước đó là việc nếu chúng ta không tìm ra
được ví dụ cụ thể để viết nội dung của Example. Lúc này chúng ta có thể lựa chọn
việc tiếp tục giải thích cho câu support. Nếu vậy cấu trúc đoạn của chúng ta sẽ thành:

Topic sentence -> Supporting sentence -> More explanation -> Concluding thought.

Hãy quan sát ví dụ dưới đây:

<p class="comment">
**(Topic sentence)**  
The reason why I object to government intervention is that it would  
hamper the private sector and simultaneously pose a huge burden on the sate.
**(Supporting sentence)**  
In countries where the government is on a tight budget and
the homeless population is large, the involvement of private property developers is
required and recommended.  
**(More explanation)**  
Not only does it release the
government from the burden of funding large-sized construction programmes but it
also fosters the housing industry.  
**(Concluding thought)**   
Given its role in attracting
public consumption and accelerating economic development, the housing industry
should be at the mercy of the market rather than the government.
</p>
                                                                  
### Phrases

Thông thường khi viết một câu trong đoạn thân bài chúng ta thường có thể thêm
một số cụm ở đầu câu để thể hiện mức độ chắc chắn của lập luận, hoặc nối ý trước
và ý sau lại với nhau, ví dụ như:

<ul class="formula">
<li>One should bear in mind the fact that S + V => Mọi người nên để ý đến thực tế là  </li>
<li>It seems to be a fact that S + V  </li>
<li>Both empirical knowledge and academic research suggest that S + V  </li>
<li>Studies have pointed to the fact that S + V => Các nghiên cứu đã chỉ ra rằng  </li>
<li>Many studies have made it clear that S + V => Nhiều nghiên cứu đã chỉ rõ là  </li>
<li>There is evidence that S + V  </li>
<li>It is common knowledge that S + V  </li>
<li>Contrary to popular belief, S + V => Trái ngược với số đông,  </li>
<li>It is well acknowledged that S + V  </li>
<li>It means that S + V => Nó có nghĩa là  </li>
<li>In this sense, S + V  </li>
<li>Not surprisingly, S + V => Không ngạc nhiên là  </li>
<li>It comes as no surprise that S + V => Không ngạc nhiên là  </li>
<li>In other words, S + V => Hay nói cách khác  </li>
<li>In plain/simple terms, S + V => Hay nói đon giản hơn,  </li>
<li>It should be noted that S + V = One should note that S + V  </li>
<li>It is important to note that S + V = It is important to realise that S + V  </li>
<li>It is not a secret that S + V  </li>
<li>There is little room for doubt that S + V = Needless to say, S + V => Chắc chắn là  </li>
<li>There is little doubt that S + V = Undoubtedly, S + V => Không nghi ngờ gì  </li>
<li>There is no denying that S + V = Undeniably, S + V => Không thể phủ nhận là  </li>
<li>It is no exaggeration to say that S + V => Không quá khi nói rằng  </li>
<li>It is clear that S + V = Clearly/Evidently, S + V => Rõ ràng là  </li>
<li>It seems obvious that S + V => Có vẻ rõ ràng là  </li>
<li>It is fair to say that = it is reasonable to say that S + V => Hợp lý khi nói rằng  </li>
<li>It is worth mentioning that S + V => Đáng đề cập là  </li>
<li>It is noteworthy that S + V => Đáng chú ý là  </li>
<li>It is likely that S + V => Có khả năng là  </li>
<li>It should be stressed that S + V  </li>
<li>it should be admitted that S + V = Admittedly, S + V => Thừa nhận là  </li>
<li>There is a growing recognition that S + V  </li>
<li>There is no guarantee/assurance that S + V => Không có gì đảm bảo là  </li>
</ul>

## Conclusion

Cách đơn giản và được dùng nhiều nhất để viết một đoạn kết bài đó là tóm tắt lại
những nội dung chính chúng ta đã viết.

Chúng ta có thể dùng một trong những cụm sau để bắt đầu phần kết luận của mình:

<ul class="formula">
<li>In conclusion,                           </li>
<li>As outlined above,  </li>
<li>To conclude,                             </li>
<li>Based on the above-mentioned facts,  </li>
<li>To sum up,                                 </li>
<li>To summarise,                            </li>
<li>From what has been discussed above,  </li>
<li>In summary,                                </li>
<li>Summing up,                              </li>
<li>According to the facts outlined above,  </li>
<li>My conclusion is that S + V                </li>
<li>According to the above analysis,         </li>
<li>From the preceding discussion,  </li>
<li>As shown above,  </li>
</ul>

Khi viết theo cách này các bạn có thể đơn giản khẳng định lại quan điểm của người
khác và quan điểm của mình để tạo thành câu kết bài. Nếu muốn gộp cả hai ý này
vào một câu chúng ta có thể sử dụng các liên từ “while, although, yet, hoặc but”.

Hãy đọc thử ví dụ sau:

<p class="comment">
In conclusion, while many object to these sports due to fatalities they trigger, I
claim that high-risk activities should not be banned.
</p>

Tóm lại, mặc dù nhiều người phản đối những hoạt động này bởi vì những cái
chết mà chúng gây ra, tôi tin rằng những hoạt động mạo hiểm không nên bị
cấm.

- object (to) (i) oppose: phản đối
- due to = because of (pre) bởi vì
- fatality = death (c) cái chết

Một câu kết luận như trên nhìn chung đã đáp ứng yêu cầu của phần này, nhưng nếu
muốn các bạn cũng có thể tổng kết thêm lý do lại sao chúng ta cho rằng như vậy. Ý này thực ra chính là nội dung của hai câu topic sentence của hai đoạn chúng ta đã
viết.

Topic sentence 1: The first reason is that in fact action sports are not as hazardous as people imagine.  
Topic sentence 2: The second reason is that such pursuits generate income for enterprises, and so provide employment to many people involved like athletes, guides, instructors, etc.

Tuy nhiên ở đây chúng ta không nên viết dài như trên mà chỉ cần tóm lại ý chính là được.
Hãy chú ý về cách sử dụng các cụm danh từ ở đây. Để ý chúng ta có thể viết hai ý này ngắn gọn thành:

Topic sentence 1 => people’s imaginary fears  
Topic sentence 2 => their economic values

Hãy quan sát:

<p class="comment">
In conclusion, while many object to these sports due to fatalities they trigger, I claim that given their economic values, high-risk activities should not be banned only because of people’s imaginary fears.
</p>

Tóm lại, mặc dù nhiều người phản đối những hoạt động này bởi vì những cái
chết mà chúng gây ra, tôi tin rằng xét những giá trị kinh tế của chúng, những
hoạt động mạo hiểm không nên bị cấm chỉ bởi vì những nỗi sợ trong trí tưởng
tượng của mọi người.

Như vậy một bài viết hoàn chỉnh cho dạng thứ nhất đã được hoàn thành, bây giờ
chúng ta hãy cùng xem kết quả khi một bài essay được tạo ra, với các phần quan
trọng được highlight.

## Full Essay

<p class="formula">
Extreme sports such as sky diving and skiing are very dangerous and should be
banned. To what extent do you agree or disagree with this view?
</p>

<p class="comment">
**In recent years**, dangerous sports **have become increasingly prevalent in** both the developing and developed world, especially among the younger generation. 
**It is argued that** such high-risk pursuits as parachuting and rock climbing, which result in a great number of fatalities every year, should be prohibited. 
**However, I completely disagree with this viewpoint and and here are my reasons.**
</p>

<p class="comment">
**The first reason is that** in fact action sports are not as hazardous as people imagine. 
These days, thanks to the scientific and technological breakthroughs, the degree of risk related to such activities is minimised. 
**For example**, participants in sports such as parachuting, motor racing, or scuba diving are always fitted with state-of-the-art equipment like protective clothing or underwater breathing apparatus. 
**This shows that** the risk of physical injuries for both amateur and professional athletes undertaking extreme sports is often kept to a minimum and it is ungrounded to prohibit them.
</p>

<p class="comment">
**Another reason against prohibiting adventure sports is that** such pursuits generate income for enterprises, and so provide employment to many people involved such as athletes, guides, instructors, etc. 
In many parts of the world, revenue from adventure activities contributes greatly to the gross domestic product. 
Nepal can be cited as a typical example since people living around the Himalayas are heavily dependent on mountaineers. 
Dangerous mountain climbing has enabled this area to thrive over the past few decades. 
**As a consequence**, the prohibition of these activities can result in fierce opposition and has a profound impact on economic prosperity of a large number of countries.
</p>

<p class="comment">
In conclusion, **while many object to** these sports due to fatalities they trigger,
**I claim that given their economic values**, high-risk activities should not be
banned only **because of people’s imaginary fears**.
</p>

(289 words)

## Examples

### Example 2

<p class="formula">
Many people today, especially in the developed world, are choosing to have fewer
children, or none at all. Do you think it is a positive or negative development?
</p>

<p class="comment">
It is true that nowadays many married couples have a predisposition to have fewer
children in many parts of the world. There is a perception that falling birth rates will
definitely have a profound impact on many different spheres, thereby impeding the
development of a nation. I completely disagree with this contention, and here are
my reasons.
</p>

<p class="comment">
People should first recognize that giving birth to only one child will lower the toil of
bringing them up. Undoubtedly, due to the ongoing escalation of almost all types of
expenses, parents often have to use most of their income to pay their kids’ tuition
fees and the family’s cost of living. So, having more than one child makes it hard for
them to maintain a high standard of living. For example, in the old days, when many
Vietnamese households had more than two children, parents generally had to work
more diligently. In their retirement years, instead of being financially independent,
most of them normally were contingent on their children’s allowance and even
became their burden. Not surprisingly, many couples are conscious of such a
potential hardship and choose a more advisable solution that is having fewer or no
children at all.
</p>

<p class="comment">
The second reason why I advocate this trend is that the single child will receive
adequate care and home schooling. In today’s society, most parents are preoccupied
with their work commitments, and so the amount of time dedicated to educating
their offspring at home is generally insufficient. In this event, having too many
children means the effectiveness of rearing them will probably diminish because,
with time constraints, it is difficult for parents to manage to complete both work
duties and childcare well simultaneously. In other words, giving birth to merely one
child will guarantee the kid more scientific parenting.
</p>

<p class="comment">
In conclusion, while many people are apprehensive about the negative effects of
declining birth rates, I firmly believe that this trend only generates more benefits for
both parents and their children.
</p>

(336 words)

- predisposition (c) khuynh hướng
- married couple (c) cặp vợ chồng
- birth rate (c) tỷ lệ sinh
- decreasing = falling = declining (adj) giảm
- have a profound effect/impact on sth: ảnh hưởng sâu sắc lên cái gì đó
- sphere = field (c) lĩnh vực
- impede = hamper = inhibit = curb = restrain (t) kìm hãm
- give birth to: sinh, đẻ
- reduce (t) decrease, decline: làm giảm
- toil (u) sự vất vả
- raise (t) bring up, nurture: nuôi, nuôi nấng
- children = offspring (plural) con cái 
- because of = due to (pre) bởi vì 
- escalation (u) sự leo thang
- devote/dedicate sth to (doing) sth: dành cái gì cho cái gì/việc gì 
- income (u) thu nhập
- tuition fees (plr) học phí 
- the cost of living (n) chi phí sinh hoạt
- diligently = hard = studiously = industriously = laboriously (adv) siêng năng, cần cù
- retirement years (plr) những năm nghỉ hưu
- instead of (pre) thay vì 
- be financially independent: độc lập về tài chính
- be contingent on sth: phụ thuộc vào cái gì đó
- allowance (c) trợ cấp
- burden (c) gánh nặng
- be aware of = be conscious of: nhận thức đượccái gì 
- advisable = wise (adj) khôn ngoan, sángsuốt
- adequate (adj) sufficient: đủ
- home schooling (u) giáo dục ở nhà
- be occupied with sth = be preoccupied with sth= be heavily loaded with: bị choán hoặc bận rộn với cái gì đó
- time constraint (c) hạn chế về thời gian
- work commitment = work duty (c) trách nhiệm công việc
- insufficient = inadequate (adj) không đủ
- generally (adv) normally: thông thường
- in this/that event: trong trường hợp này
- mean (t) có nghĩa, đồng nghĩa
- manage to do sth: xoay xở để làm gì đó
- effectiveness (u) sự hiệu quả
- diminish = decrease (i/t) (làm) giảm
- It is hard/difficult for sb to do sth: khó để ai làm gì 
- childcare (u) việc chăm sóc con cái 
- at the same time = simultaneously (adv) cùng một lúc, đồng thời 
- scientific (adj) khoa học
- be apprehensive/anxious about sth: lo lắng về điều gì đó
- firmly (adv) một cách vững chắc

### Example 3

<p class="formula">
Living in a foreign country can cause more problems than benefits it brings? To what extent do you agree or disagree with this statement?
</p>

<p class="comment">
It seems obvious that because of globalization, many people have an inclination to
migrate to other countries for working or studying. There is a perception that it is not a
good idea since living in a utterly unfamiliar country can generate many obstacles
rather than bringing benefits. I completely disagree with this contention and here are
my reasons.
</p>

<p class="comment">
It should be first noted that migrants to another more developed country may probably
do an array of ordinary jobs, even manual ones, with much a higher remuneration than
in their motherland. Needless to say, developed countries such as America, Germany,
or Australia generally have a higher minimum wage for laborers than a majority of
Asian or African nations. For example, only by doing blue-collar work like taxi driving,
livestock slaughter, or childcare can an immigrant earn a few thousands of dollars each
month, which is undoubtedly the aspiration of most graduates, engineers, doctors or
even business executives in the developing world. This shows that migrating abroad for
work creates tangible benefits for people, especially those from disadvantaged areas
</p>

<p class="comment">
Another reason why I contend that living in a different country is advantageous is that
it helps develop self-reliance and capacity to work independently. More specifically,
overcoming homesickness and the feeling of missing relatives, together with solving
work problems on their own, will help these individuals to be more mature and
knowledgeable. There is a growing recognition that the majority of both students and
workers coming back from abroad after study and work periods generally have more
hands-on experience, better life skills, and ability to communicate than their peers
living at home. A society composed of such individuals will certainly benefit
enormously.
</p>

<p class="comment">
Based on the above-mentioned facts, although there are arguments against settling in
another country, I believe that it is a great chance to sample a new environment.
</p>

(306 words)

- have a tendency/inclination to do something:
có khuynh hướng làm gì đó
- globalization (u) sự toàn cầu hóa
- completely = utterly (adv) hoàn toàn
- strange = unfamiliar (adj) xa lạ
- rather than (phrase) hơn là
- benefit (c) advantage: lợi ích
- beneficial = advantageous (adj) có ích, mang
lại lợi ích
- migrant (c) người di cư
- developed (adj) phát triển
- manual/blue-collar work (u) công việc chân
tay
- minimum (adj) tối thiểu
- etc. = and so on = and so forth = to name but a
few: vân vân
- childcare (u) chăm sóc trẻ em
- immigrant (c) người nhập cư
- undoubtedly = no doubt (adv) chắc chắn
- aspiration = desire (c) khát khao
- graduate (c) sinh viên tốt nghiệp
- business executive (c) nhà điều hành doanh nghiệp
- a developing country = an underdevelopedcountry = a less developed country (n) một nước đang/kém phát triển
- tangible (adj) hữu hình
- disadvantaged = deprived (adj) thiếu thốn, thiệt thòi 
- independence = self-dependence =
self-reliance = autonomy (u) sự tự lập, tính tự lập
- capacity (c/u) khả năng
- homesickness (u) sự nhớ nhà
- along with = together with: cùng với 
- mature = grown up (adj) trưởng thành
- knowledgeable (adj) có kiến thức
- worker (c) labourer: người lao động
- hands-on experience (u) kinh nghiệm thực tế
- life skill (c) kỹ năng sống
- peer (c) người đồng trang lứa
- be composed of: tạo thành bởi 
- experience = undergo = sample (t) trải nghiệm

### Example 4

<p class="formula">
Foreign visitors should pay more than local visitors for cultural and historical
attractions. To what extent do you agree or disagree with this opinion?
</p>

<p class="comment">
Transnational travel has become commonplace in almost all parts of the world over
the past few decades. Many people claim that foreign visitors should be charged
higher prices than local inhabitants when sightseeing in historical and cultural
attractions. As far as I am concerned, this point of view is not justified and here are
my reasons.
</p>
<p class="comment">
The first reason is that the discrimination between locals and foreign tourists can
have a detrimental impact on the collaboration and friendship between countries.
This favouritism runs counter to the current globalization in which global citizens,
regardless of nationality and language, share the same rights and responsibilities
anywhere across the world. For example, many regions such as EU and ASEAN have
allowed citizens to freely travel in the joint territory. The objective of this move is to
promote the cooperation between member states and give a boost to the economic
growth of the entire region. This explains why charging foreigners higher prices is not
put into practice in most countries around the world.
</p>
<p class="comment">
People should meanwhile note that overseas tourists make a significant contribution
to the local economy via their expenditure on various commodities and services such
as food products, souvenirs, accommodation, etc. If the local government does not
raise entrance fees for visiting heritage sites, they will always receive a stable
number of visitors. As a result, the entire tourist industry and other economic sectors
such as hospitality, retail and transportation will benefit. Vietnam can be cited as a
typical example because tourist attractions here always charge foreign and local
tourists identical prices. For this reason, my country is always among the destinations with a huge influx of visitors from exotic cultures. This has made
dwellers’ life in tourist cities here become more prosperous than other places over
the last few decades.
</p>
<p class="comment">
In conclusion, I believe that local governments should not adopt such a pricing policy
because it could inflict damage on the local economy in the longer term.
</p>
(327 words)

- transnational travel (u) du lịch xuyên quốc gia
- decade (c) thập kỷ
- foreign/overseas visitor (c) khách du lịch nước ngoài 
- charge (t) tính tiền ai đó
- discrimination (u) sự phân biệt
- have an effect on sth = have an impact on sth = have (an) influence on: ảnh hưởng đến cái gì 
- cooperation = collaboration (u) sự hợp tác
- friendship (u) sự hữu nghị 
- favouritism = partiality = preferential treatment = preference (u) sự thiên vị 
- go against sth = run counter to sth: đi ngược lại cái gì đó
- globalization (u) sự toàn cầu hóa
- global citizen (c) công dân toàn cầu
- regardless of = irrespective of (pre) bất kể, không phân biệt
- nationality (c) quốc tịch
- territory (u) lãnh thổ
- joint = shared (adj) chung
- accelerate = give a boost to: thúc đẩy
- apply = put sth into practice: áp dụng
- contribute (to) (v) đóng góp
- through = via (pre) thông qua
- various = a wide range of: nhiều loại khác nhau
- commodities = goods (plr) hàng hóa
- food product = foodstuff (c) thực phẩm
- accommodation = housing (u) nơi ăn ở
- visit (t) sight-see (in): thăm, tham quan
- stable (adj) ổn định
- along with = together with: cùng với 
- hospitality (u) ngành nhà hàng khách sạn
- retail (u) ngành bán lẻ
- benefit (i) hưởng lợi 
- be considered (to be) sth = be regardedas sth = be viewed as sth: được xem như là cái gì 
- typical (adj) điển hình
- destination (c) điểm đến
- influx = inflow (c) sự đổ dồn, sự chảy vào
- exotic (adj) ngoại lai, nước ngoài 
- resident = inhabitant = dweller (c) cưdân
- prosperous = flourishing = thriving (adj) phát đạt
- inflict damage on sb/sth = damage sth: gâyhại cho cái gì đó
- in the long term = in the long run: trong dài hạn

# ARGUE BOTH SIDES

Đối với các câu hỏi thuộc dạng này như đã đề cập ở phần đầu, nếu như chúng ta
không muốn lập luận theo một hướng thì có thể lựa chọn cách thứ hai này. Có nghĩa
là thay vì chỉ chọn một hướng (ví dụ chỉ chọn agree hoặc disagree) bài viết của chúng
ta có thể bao gồm cả hai.

Khi lập luận theo cách này chúng ta chỉ cần điều chỉnh một chút về cách đưa ra ý kiến
của mình ở các phần introduction và conclusion. Trong khi đó hai phần body
paragraphs chúng ta sẽ viết về hai luận điểm trái ngược nhau thay vì tương đồng
nhau như cách thứ nhất.

Để nắm được sự khác nhau như thế nào của cách làm này so với cách thứ nhất các
bạn tiếp tục đọc cách lập luận cho ví dụ dưới đây.

Example 1

<p class="formula">
Some people think that employers should not care about the way their employees
dress, because what matters is the quality of their work. To what extent do you agree or disagree with this point of view?
</p>

Một số người nghĩ rằng những người chủ không nên quan tâm về cái cách nhân viên
của họ ăn mặc bởi vì điều quan trọng là chất lượng công việc của họ.
Bạn đồng ý hay không đồng ý với quan điểm trên đến mức độ nào?

- employer (c) người chủ                         
- matter (i) to be important: quan trọng
- employee = worker = member of staff (c) nhân   
- dress (i+pre/adv) ăn mặc viên

## Introduction

Tương tự phần introduction này chúng ta cũng có thể bao gồm ba phần là:

* Background information
* People’s opinion
* Your opinion

### Background Information

Phần background chúng ta vẫn viết một câu bình thường nêu lên tình hình chung
hiện nay của việc ăn mặc ở nơi công sở.

<p class="comment">
Today there are plenty of opposing opinions about whether organisations should have mandatory dress codes or not.
</p>

Ngày nay có khá nhiều quan điểm trái chiều về việc các tổ chức có nên có những quy định bắt buộc về quần áo của nhân viên hay không.


- opposing (adj) conflicting, opposite: trái chiều   
- compulsory (adj) = mandatory: bắt buộc
- regulation (c) quy định
- Trong bài này sẽ đề cập nhiều về quy định ăn mặc là “dress code”, chúng ta có thể paraphrase nó
thành regulations about staff clothing hoặc rules related to staff clothes.

### People’s opinion

Sau khi xong phần background chúng ta sẽ tương tự đưa ra phần quan điểm của mọi
người, phần này chúng ta sẽ chọn đại một hướng nào đó giống dạng trước.

<p class="comment">
Many people argue that these rules should not be perceived to be crucial in present-day working environments.
</p>

Nhiều người cho rằng những quy định này không nên được xem là quan trọng trong môi trường làm việc hiện đại.

- perceive sth to be noun/adj: xem cái gì như cái gì hoặc như thế nào
- crucial (adj) very important/significant: rất quan trọng
- work environment = working environment (c) môi trường làm việc

### Your opinion

Một lần nữa cần lưu ý rằng đây luôn là phần quan trọng nhất của mở bài vì nó sẽ
giúp trả lời yêu cầu của đề bài.

Ở trong phần này các bạn cần đưa ra ý kiến của mình. Đây là phần khác biệt so với
cách viết theo một hướng. Bởi vì chúng ta đã xác định là mình sẽ chọn cả hai hướng
nên câu đưa ra ý kiến của các bạn ở phần mở bài này sẽ phải thể hiện rõ ý này.
Vì hai hướng này trái chiều nhau chúng ta sẽ cần dùng một liên từ là “while” hoặc
“although” với chung nghĩa là “mặc dù” để viết câu opinion của mình, hoặc chúng ta
cũng có thể dùng hai liên từ “yet (tuy nhiên)” hoặc “but (nhưng)”.

Trước hết hãy đọc thử các ví dụ sau:

<p class="comment">
Although/while I am partly supportive of this point of view, I also believe that
wearing formal clothes is still needed in specific work contexts.
</p>

<p class="comment">
I partly agree with this point of view, but/yet I believe that wearing formal
clothes is still needed in specific work contexts.
</p>

Mặc dù tôi phần nào đồng ý với quan điểm trên, nhưng tôi cũng tin rằng mặc
quần áo trang trọng vẫn cần thiết trong những hoàn cảnh làm việc đặc biệt.

- clothes = clothing = attire = garment =  wardrobe (n) quần áo       
- work context= wok situation = work circumstance (c) hoàn cảnh làm việc
- formal (adj) trang trọng

Chúng ta thường thêm những từ, cụm từ như “partly” “in part” “to some
extent/degree” “to a certain extent/degree” để thể hiện mình chỉ đồng ý phần nào
với quan điểm này và mở ra vế thứ hai với ý kiến trái ngược như trong câu ở trên.

Một số cách hay dùng như:

<ul class="formula">
<li>While I partly agree with the above viewpoint, I also believe that S + V</li>
<li>Although I agree with the above viewpoint to some extent, I also believe that S+V</li>
<li>To some extent I agree with the above viewpoint, but I also believe that S + V</li>
<li>I partly agree with the above viewpoint, yet I also believe that S + V</li>
</ul>

Như vậy chúng ta sẽ có phần mở bài như sau:

<p class="comment">
Today there are plenty of opposing opinions about whether organisations
should have mandatory dress codes or not. Many people argue that these
rules should not be perceived to be crucial in present-day working
environments. Although I am partly supportive of this point of view, I also
believe that wearing formal clothes is still needed in specific work contexts.
</p>

Đọc phần mở bài này chúng ta sẽ thấy rằng chỉ có câu cuối khác với cách viết thứ
nhất, còn lại mọi thứ đều tương tự.

## Body

Sau khi viết xong phần mở bài chúng ta đã xác định được quan điểm của mình là cả hai hướng. Vì vậy mỗi phần thân bài của chúng ta sẽ bảo vệ một hướng.

### Body paragraph 1

Câu topic sẽ là một luận điểm chính của đoạn thứ nhất, giải thích tại sao chúng ta cho
rằng nhân viên không cần mặc quần áo trang trọng.

Chúng ta có thể dùng một số cụm dưới đây để bắt đầu câu topic nhằm thể hiện rằng
đoạn này sẽ nói về một hướng và đoạn sau là một hướng khác.

<ul class="formula">
<li>On the one hand,</li>
<li>On the positive/negative side,</li>
<li>Admittedly,</li>
<li>Unarguably,</li>
<li>Undeniably,</li>
<li>The is no denying that S + V</li>
<li>It is important to recognize that S + V</li>
<li>There is little doubt that S + V</li>
</ul>

Ví dụ chúng ta có thể viết một câu topic để ủng hộ hướng thứ nhất đó là mặc quần
áo trang trọng là không cần thiết.

<p class="comment">
On the one hand, as a matter of fact, formal clothing does not make a
substantial contribution to the improvement of labour productivity, which is
the more important factor determining a company’s success.
</p>

Một mặt, thực tế quần áo trang trọng không đóng góp nhiều vào việc tăng
năng suất lao động, đây là yếu tố quan trọng hơn quyết định sự thành công
của một công ty.

Các phần sau chúng ta sẽ trình bày tương tự như một body paragraph bình thường.

<p class="comment">
**(Topic sentence)**  
On the one hand, as a matter of fact, formal clothing does not make a substantial contribution to the improvement of labour productivity, which is the more important factor determining a company’s success.  
**(Supporting sentence)**  
In simple terms, when employees have to wear clothes under a certain rule, they would customarily expend quite a lot of time on their appearance, and are apprehensive about sanctions after offending the code. Not surprisingly, such external distractions would perhaps have an adverse impact on the quality of work.   
**(Example)**  
Being conscious of this issue, many large corporations such as Google or Facebook have chosen to encourage their employees to dress casually at work, and even senior managers also normally wear only jeans and T-shirts.   
**(Concluding thought)**   
Evidently, the global success of these two companies reflects the fact that dress codes are not invariably of importance in all fields.
</p>

Một mặt, thực tế quần áo trang trọng không đóng góp nhiều vào việc tăng
năng suất lao động, đây là yếu tố quan trọng hơn quyết định sự thành công
của một công ty. Khi nhân viên phải mặc quần áo theo một quy định nào đó,
họ sẽ thường phải dành nhiều thời gian cho vẻ ngoài của mình, và lo lắng về
hình phạt khi vi phạm nội quy. Những điều gây xao lãng bên ngoài như vậy
chắc chắn sẽ ảnh hưởng tiêu cực nên chất lượng công việc. Nhận thức được
vấn đề này, nhiều tập đoàn lớn như Google hay Facebook luôn khuyến khích
nhân viên mặc thoải mái ở nơi làm việc, và thậm chí những quản lý cấp cao
cũng thường chỉ mặc jeans hay áo thun. Rõ ràng là sự thành công trên toàn
cầu của hai công ty này đã phản ánh thực tế là quy định về ăn mặc không phải
luôn quan trọng trong tất cả các lĩnh vực.


- in fact (phr) as a matter of fact: trong thực tế
- contribute (to) (t) make a contribution to:
đóng góp vào
- substantial (adj) đáng kể
- labour productivity (u) năng suất lao động
- certain (adj) nào đó
- appearance (u) ngoại hình, vẻ ngoài 
- sanction = punishment (c) hình phạt
- offend = violate = break (t) vi phạm
- external (adj) outside: bên ngoài 
- distraction (c) điều gây xao lãng
- be aware of = be concious of: nhận thức được
điều gì 
- corporation c) tập đoàn
- encourage sb to do sth: khuyến khích ai làm gì
đó
- dress casually/informally: ăn mặc thoải mái 
- executive (c) senior manager: quản lý cấp cao
- evidently (adv) rõ ràng
- reflect (t) phản ánh
- invariably (adv) luôn luôn, không thay đổi 
- essential = crucial = vital = very important (adj)
rất quan trọng
- sector = field = domain = sphere (c) lĩnhvực

### Body paragraph 2

Sau khi hoàn thành body paragraph 1, bây giờ chúng ta cần viết một đoạn body với
quan điểm ngược lại.

Chúng ta có thể dùng những cụm sau trong phần đầu của câu topic của đoạn thứ hai
này, mục đích để thể hiện sự khác nhau về nội dung giữa hai đoạn:

<ul class="formula">
<li>On the other hand,</li>
<li>However,</li>
<li>Nevertheless,</li>
<li>Despite the arguments mentioned above,</li>
<li>In spite of the above-mentioned arguments ,</li>
<li>Despite the negatives mentioned above,</li>
<li>Despite the above-mentioned downsides,</li>
<li>Despite the positives mentioned above,</li>
<li>Despite the justifications given for X,</li>
<li>Despite what has been discussed above,</li>
</ul>

Ví dụ:

<p class="comment">
On the other hand, I also claim that formal attire is the contributing factors in
the formation and enhancement of company image.
</p>

Mặt khác, tôi cũng cho rằng quần áo trang trọng là nhân tố đóng góp vào việc
hình thành và nâng cao hình ảnh của công ty.

Viết tiếp các phần sau các bạn sẽ có một đoạn thân bài hoàn chỉnh như sau:

<p class="comment">
**(Topic sentence)**  
On the other hand, I also claim that formal attire is the contributing factors in the formation and enhancement of company image.  
**(Supporting sentence)**  
Needless to say, with the increasingly fierce competition on the market today, the possession of a professional image is a prerequisite for grabbing customers’ attention, and employee uniforms are among the elements creating professionalism.  
**(Example)**  
For example, almost all staff members of airlines, including flight stewards and pilots, have to wear uniforms in the workplace. Similarly, most enterprises in such fields as banking, the health sector and retail have compulsory rules concerning staff clothes.  
**(Concluding though)**  
This demonstrates that dress codes play a prominent role in the operation of many businesses.
</p>

Mặt khác, tôi cũng cho rằng quần áo trang trọng có đóng góp quan trọng
trong việc hình thành và nâng cao hình ảnh của công ty. Với sự cạnh tranh
ngày càng khốc liệt trên thị trường ngày nay, việc sở hữu một hình ảnh chuyên
nghiệp và khác biệt là tiền đề thu hút sự quan tâm của khách hàng và đồng
phục của nhân viên chính là một trong những yếu tố tạo ra sự chuyên nghiệp.
Ví dụ như gần như tất cả các hãng hàng không đều bắt buộc nhân viên, bao
gồm phi công và tiếp viên hàng không, phải mặc đồng phục khi làm việc.
Tương tự, hầu hết các doanh nghiệp trong các lĩnh cực như ngân hàng, y tế,
bán lẻ đều có những quy định bắt buộc về việc ăn mặc của nhân viên. Chính vì
vậy, những quy định ăn mặc đóng vai trò quan trọng trong hoạt động của
nhiều doanh nghiệp.

## Conclusion

Phần kết bài tương tự chúng ta cũng sử dụng các cụm như 

* in conclusion
* to conclude 
* to sum up 

như ở phần trước.

Nội dung của phần này đơn giản chúng ta chỉ cần viết lại câu ý kiến cá nhân bao gồm
hai hướng khác nhau như trong phần your opinion của introduction. Hãy paraphrase
để tránh lặp lại những từ đã sử dụng.

<p class="comment">
In conclusion, while I advocate regulations related to staff clothes at work to some extent, I do not believe that they are applicable to all professions or economic sectors.
</p>

Tóm lại, mặc dù tôi ủng hộ những quy định ăn mặc bắt buộc ở nơi làm việc, tôi không cho rằng chúng phù hợp cho tất cả các ngành nghề hoặc lĩnh vực kinh tế.

- sector of the economy = economic sector (c) lĩnh vực kinh tế
- occupation = job = profession = vocation (c) ngành, nghề

Tương tự như phần trước trong một số trường hợp viết đến đây vẫn chưa đủ từ yêu
cầu các bạn có thể lặp lại phần nguyên nhân ở phía sau mỗi vế.

Ví dụ:

<p class="formula">
In conclusion, while I advocate regulations related to staff clothes at work to some extent because (of)..., I do not believe that it is applicable for all professions or economic sectors since/due to...
</p>

- because = since = as (conj) bởi vì                  - because of = due to (pre) bởi vì


Các bạn có thể viết một trong hai hoặc cả hai ý này đều được, tuy nhiên hãy cẩn thận
để tránh bị lặp từ.
Như đã hướng ,những câu sau because thực ra là từ ý của câu topic của chúng ta ở
cả hai đoạn.
Trong ví dụ này vì vế đầu dễ hơn nên mình đề cập lại đơn giản như sau:

<p class="comment">
In conclusion, while I advocate regulations related to staff clothes at work to some extent because they augment the credibility of an organisation in the eyes of clients, I do not believe that they are applicable to all professions or economic sectors.
</p>

- augment = increase (t) làm tăng                     - client = customer (c) khách hàng
- credibility (u) sự tin cậy, đáng tin





Như vậy một bài viết hoàn chỉnh cho cách viết thứ hai đối với dạng câu hỏi đầu đã
được hoàn thành, bây giờ chúng ta hãy cùng xem kết quả khi một bài essay hoàn
chỉnh được tạo ra, với các phần quan trọng được highlight.

## Full Essay

<p class="formula">
Some people think that employers should not care about the way their employees
dress, because what matters is the quality of their work. To what extent do you agree or disagree with this point of view?
</p>

<p class="comment">
**Today there are plenty of opposing opinions about whether** organisations should have mandatory dress codes or not. 
**Many people argue that** these rules should not be perceived to be crucial in present-day working environments. 
**Although I am partly supportive of this point of view, I also believe that** wearing formal clothes is still needed in specific work contexts.
</p>

<p class="comment">
**On the one hand**, as a matter of fact, formal clothing does not make a substantial contribution to the improvement of labour productivity, which is the more important factor determining a company’s success. 
**In simple terms**, when employees have to wear clothes under a certain rule, they would customarily expend quite a lot of time on their appearance, and are apprehensive about sanctions after offending the code. 
**Not surprisingly**, such external distractions would perhaps have an adverse impact on the quality of work. Being conscious of this issue, many large corporations such as Google or Facebook have chosen to encourage their employees to dress casually at work, and even senior managers also normally wear only jeans and T-shirts.
**Evidently**, the global success of these two companies **reflects the fact that** dress codes are not invariably of importance in all fields.
</p>

<p class="comment">
**On the other hand, I also claim that** formal attire is the contributing factors in the formation and enhancement of company image. 
**Needless to say**, with the increasingly fierce competition on the market today, the possession of a professional image is a prerequisite for grabbing customers’ attention, and
employee uniforms are among the elements creating professionalism. 
**For example**, almost all staff members of airlines, including flight stewards and pilots, have to wear uniforms in the workplace. 
**Similarly**, most enterprises in such fields as banking, the health sector and retail have compulsory rules concerning staff clothes. 
**This demonstrates that** dress codes play a prominent
role in the operation of many businesses.
</p>

<p class="comment">
In conclusion, **while** I support regulations related to staff clothes at work to some extent **because** they augment the credibility of an organisation in the
eyes of clients, **I do not believe that** they are applicable to all professions or economic sectors.
</p>

(351 words)

## Examples

### Example 2

<p class="formula">
Some universities now offer their courses on the internet so that people can study
online. Is this a positive or negative development?</p>
</p>

<p class="comment">
It is true that nowadays with technological advances and the Internet online courses
have become a universal feature of tertiary education. Some people hold the view
that internet-based learning creates many difficulties for learners’ assimilation of
knowledge. Although I agree with this above point of view to some extent, I claim
that online studying also generates certain benefits for students.
</p>

<p class="comment">
On the one hand, the drawback is that online courses generally restrict students to
only theoretical knowledge. Virtual classes are always deficient in practice sessions,
face-to-face instruction from lecturers, as well as discussion and exchange of ideas
among learners. It should be noted that nowadays many graduates from formal
education are still judged to be short of hands-on knowledge and experience.
Therefore, it is difficult for distance training through only video lessons can equip
students with functional skills recruiters often demand. This can be perceived as the
greatest limitation of an online class compared to a conventional one.
</p>

<p class="comment">
Despite the negatives mentioned above, I also affirm that online courses make it
possible for students to study flexibly. It is important to realise that many people
wish to obtain a university degree, yet have unfavourable circumstances due to
geographical distance or tight schedule. For example, it is almost infeasible for those
women who are preoccupied with childcare to enrol in direct courses in educational
institutions. In such cases, distance training courses could be the only solution for
them to graduate from university, thereby improving their career prospects. This
reflects that numerous individuals are likely to benefit from such a new educational
model.
</p>

<p class="comment">
According to the above analysis, while I acknowledge some limitations of online learning, I believe that it is a positive development overall.
</p>

(285 words)

### Example 3

<p class="formula">
Many people think that living alone causes more problems than benefits it brings?
To what extent do you agree or disagree with this statement?
</p>

<p class="comment">
In recent years, the tendency towards living independently has become increasingly
prevailing in both the developed and developing world. Some claim that this
predisposition should not be encouraged because of several negative repercussions
it has for loners. While I partly agree with this contention, I also believe that this
lifestyle brings certain benefits.
</p>

<p class="comment">
On the one hand, loners usually do not have friends or family members to share
hardships they are confronted with. These individuals have to carry out all the work
such as paying monthly bills, time and budget management, cooking, cleaning as well
as dealing with workplace issues without the assistance and encouragement of their
relatives. Needless to say, without stable income and willpower, this independent
way of living is likely to make them experience loneliness, apprehension, depression
or even reach an impasse. As a result, the decision to live separately from parents is
not always advisable when that person has not come of age and been self-confident
enough.
</p>

<p class="comment">
Despite the arguments mentioned above, I also claim that living without the
protection of parents could be worthwhile and advantageous to the youth. Because
of having to undertake all life tasks on their own, such individuals gradually become
self-reliant and acquire valuable life skills. Consequently, they learn how to be
accountable for whatever they have done and can survive any harsh environment
later on. For example, a great number of the richest people in the world are
self-made billionaires such as Mark Zuckerberg, Warren Buffett and Jack Ma, who all
lived independently and started their career from a very young age. Their success has
inspired younger generations in all corners of the world and simultaneously reflects
the fact that self-sufficient people will only benefit society.
</p>

<p class="comment">
From the preceding discussion, although I acknowledge that an upsurge in the
number of those living alone can cause some minor problems for themselves, this
tendency has its own positive dimensions.
</p>

(318 words)

# DISCUSS BOTH VIEWS

Đây là dạng câu hỏi thứ hai chúng ta sẽ hay gặp trong bài Task 2. Dạng này sẽ thường
có kiểu câu hỏi “Discuss both of the views and give your own opinion” ở cuối đề.

Lưu ý là nhiều trường hợp đề bài cũng có thể không yêu cầu chúng ta đưa ra ý kiến
cá nhân của mình, mà đơn giản chỉ bắt chúng ta thảo luận về hai hướng thôi. Thực ra
nếu đề bài yêu cầu như vậy thì chúng ta cũng chỉ cần bỏ đi một số câu thể hiện quan
điểm cá nhân. Hay nói cách khách điều này chỉ làm bài viết của chúng ta khác về hình
thức còn nội dung sẽ không có gì thay đổi.

Hãy đọc một số ví dụ dưới đây để thấy điều khác biệt:

1. Some people believe that schoolchildren should not be given homework by their
teachers, whereas others argue that homework plays an important role in the
education of children.
Discuss both of these views and give your own opinion.

2. Some people believe that teachers should be responsible for teaching students to
judge right and wrong and to behave well. Some say that teachers should only teach
students about academic subjects.
Discuss both views and give your opinion.

3. It is not uncommon that children are required to obey the rule of their parents and
teachers. Some people are worried that too much control over children will not
prepare them well for their adult life.
Discuss both sides and give your opinion.

4. Discuss the advantages and disadvantages of playing sports and participating in
physical exercise.

5. Discuss the arguments for and against raising pets.

Trong các ví dụ này các bạn thấy ví dụ 4 và 5 mặc dù yêu cầu thảo luận cả hai hướng
nhưng không có yêu cầu chúng ta đưa ra ý kiến cá nhân. Tuy nhiên chúng ta sẽ
thường gặp dạng câu hỏi 1,2,3 hơn.
Vì vậy dưới đây là một ví dụ về cách trình bày khi các bạn gặp hỏi câu hỏi này.

 Example 1

<p class="formula">
Some people believe that schoolchildren should not be given homework by their
teachers, whereas others argue that homework plays an important role in the
education of children. Discuss both of these views and give your own opinion.
</p>

 Một số người tin rằng học sinh không nên được giao bài tập về nhà bởi giáo viên,
 trong khi đó những người khác cho rằng bài tập về nhà đóng một vai trò quan trọng
 đối với việc giáo dục trẻ em.

 Thảo luận cả hai quan điểm trên và đưa ra ý kiến của bạn.

 - schoolchild (c) (plural: schoolchildren) học sinh
 - play an important role in (doing) sth = have an important role to play in (doing) sth: đóng vai trò
 quan trọng trong
 - homework (u) homework assignment, homework exercise: bài tập về nhà

## Introduction

Có hai cách để chúng ta trình bày khi gặp câu hỏi này. Thứ nhất một điều chắc chắn đó
là bài viết phải viết về hai hướng khác nhau. Thứ hai các bạn phải xác định hai ý kiến
trái chiều nhau này là ý kiến của ai.
Trong trường hợp cả hai ý kiến này đều là của các bạn thì bố cục của chúng ta là:

* While I partly..., I also believe that ...
* Your opinion -> One side
* Your opinion-> The opposite side
* Restate your opinion

Tuy nhiên còn một cách khác đó là chúng ta vẫn thảo luận về hai hướng nhưng chúng
ta chỉ đồng ý với một hướng. Hướng còn lại là quan điểm của những người khác. Lúc
này bố cục của chúng ta sẽ trở thành:

* Some people argue that S + V. However, I disagree with this view and here are my reasons
* People’s opinion => One side
* Your opinion => The opposite side
* Restate your opinion

Như vậy chúng ta sẽ thấy tùy vào cách chúng ta lựa chọn thì cách sắp xếp thông tin ở
phần Introduction và mỗi đoạn thân bài sẽ có một chút khác biệt, dù khác biệt là không
quá lớn.

Như đã nói chúng ta đã biết viết theo cách thứ nhất, vậy nên bây giờ chúng ta sẽ thử
trình bày theo cách thứ hai.

Đầu tiên một phần introduction cũng sẽ vẫn bao gồm ba phần:

Background information => People’s opinion => Your opinion

Các bạn hãy hình dung thân bài sẽ là hai hướng khác nhau trong đó một hướng là của
những người khác, còn lại là của chúng ta. Thì chẳng khác nào cách viết một phần
introduction của dạng đầu tiên.

Hãy quan sát lại cách viết mở bài cho dạng đầu tiên (give an opinion, argue one side)
chúng ta sẽ thấy nó hoàn toàn tương tự:

<p class="comment">
**(Background information)**  
In recent years, dangerous sports have become increasingly prevalent in both the developing and developed world, especially among the younger generation.  
**(People’s opinion)**  
It is argued that such high-risk pursuits as parachuting and rock climbing, which result in a great number of fatalities every year, should be prohibited.  
**(Your opinion)**  
However, I completely disagree with this viewpoint and and here are my reasons.
</p>

Đây không phải là trùng hợp ngẫu nhiên bởi vì dạng thứ nhất chúng ta cũng chọn một
hướng và cố tình chèn phần People’s opinions vào introduction để dễ triển khai hơn.

### Remarks

Nhưng trong dạng câu hỏi này lưu lý một điều là hãy để hai phần People’s opinion và
Your opinion trái ngược nhau vì câu hỏi yêu cầu chúng ta thảo luận hai hướng khác
nhau.

**(Background information)**  
Today there are plenty of opposing opinions about whether schoolchildren should be given homework by their teachers.
**(People’s opinion)**  
Many people argue that assignments given to complete at home do not make a significant contribution to the effectiveness of education.
**(Your opinion)**  
However, I disagree with this point of view and my reasons are as follows.

Ngày nay có nhiều quan điểm trái chiều về việc học sinh có nên được giao bài
tập về nhà bởi giáo viên hay không. Nhiều người cho rằng bài tập được giao
để hoàn thành ở nhà không góp phần vào việc nâng cao hiệu quả giáo dục học
sinh. Tuy nhiên tôi không đồng ý với quan điểm này và dưới đây là lý do tại
sao.

  - give/set/assign sb homework: giao bài tập về nhà cho ai đó
  - contribute to = make a contribution to: góp phần vào

## Body

### Body paragraph 1

Trong đoạn thân bài đầu tiên chúng ta nên nhấn mạnh đây là ý kiến của những người
khác. Và đoạn thứ hai chúng ta sẽ đưa ra quan điểm của mình. Điều này sẽ khớp với
cách sắp xếp hai luồng ý kiến ở phần mở bài.

Để thể hiện đoạn thứ nhất là ý kiến của những người khác chúng ta có thể thay phiên
để những phần sau vào các câu trong đoạn thân bài này:

<ul class="formula">
<li>Many people believe/claim/argue that S + V</li>
<li>It is often believed/argued/claimed that S + V</li>
<li>Those who oppose/advocate + N/$V_ing$ believe that S + V. </li>
<li>This argument highlights/emphasizes that S + V (chỉ sử dụng từ câu thứ hai)</li>
<li>According to this view, S + V (chỉ sử dụng từ câu thứ hai)</li>
</ul>

- highlight = emphasize (t) nhấn mạnh        
- advocate (t) support: ủng hộ
- oppose (t) object to: phản đối

Hãy quan sát:

Đây là đoạn thân bài bình thường chúng ta sẽ viết:

<p class="comment">
**(Topic sentence)**  
On the one hand, homework places an unneeded burden on school pupils, who are already under too much pressure from learning at school.  
**(Supporting sentence)**  
Unlike in past times, schoolchildren nowadays must dedicate most of their daytime to attending school and digesting a sheer volume of academic knowledge.  
**(More explanation)**  
As a result, if students are compelled to study further at home, they would be deficient in time for relaxation and recreational activities.  
**(Concluding thought)**  
For this reason, this can eventually lead to schoolchildren’s loss of motivation and interest in learning.
</p>

Đây là đoạn thân bài sau khi đã thêm các phần trên:

<p class="comment">
**(Topic sentence)**  
On the one hand, it is argued that homework places an unneeded burden on school pupils, who are already under too much pressure from learning at school.  
**(Supporting sentence)**  
This argument highlights that, unlike in past times, schoolchildren nowadays must dedicate most of their daytime to attending school and digesting a sheer volume of academic knowledge.  
**(More explanation)**  
As a result, if students are compelled to study further at home, they would be deficient in time for relaxation and recreational activities.  
**(Concluding thought)**  
For this reason, those who oppose the setting of homework assignments believe that this can eventually lead to schoolchildren’s loss of motivation and interest in learning.
</p>

Một mặt người ta cho rằng bài tập về nhà tạo ra một gánh nặng không cần
thiết lên học sinh, những người cũng đang chịu rất nhiều áp lực từ việc học ở
trên trường. Quan điểm này nhấn mạnh rằng không giống như trong quá khứ
ngày nay học sinh phải dành hầu hết thời gian trong ngày của mình ở trường
và tiêu hóa một khối lượng rất lớn kiến thức học thuật. Kết quả là khi bị ép
học thêm ở nhà, học sinh sẽ thiếu thời gian để nghỉ ngơi và cho các hoạt động
giải trí. Vì lý do này những người phản đối việc giao bài tập về nhà tin rằng
điều này có thể làm cho chúng mất đi động lực và hứng thú học tập.

- burden (c) (on sb): gánh nặng
- be under pressure: chịu áp lực
- devote/delicate time to (doing) sth: dành thời gian làm cái gì - digest (t) tiêu hóa
- a sheer volume (n) khối lượng rất lớn
- lack sth = be deficient in sth = be short of sth: thiếu cái gì đó
- recreational (adj) entertaining: giải trí 
- compel (t) obligate, force (sb to do sth): ép ai làm gì - lead to = result in: dẫn đến

Ngoài ra để ý chúng ta vẫn có thể dùng các cụm kiểu như “on the one hand” trong câu topic của đoạn này như trên vì 2 đoạn thân bài có nội dung tương phản nhau. (Hãy xem lại các cụm tương đồng với “on the one hand” ở dạng trước”)

### Body Paragraph 2

Đoạn thân bài thứ hai là đoạn để đưa ra ý kiến cá nhân của chúng ta. Tương tự với
phần đưa ra ý kiến cá nhân theo hai hướng, các bạn có thể dùng các cụm kiểu như ”on
the other hand” (xem lại các cách viết tương đồng khác ở dạng trước)

Hãy quan sát đoạn thân bài sau:

<p class="comment">
**(Topic sentence)**  
In spite of the arguments mentioned above, I personally   believe that thanks to exercises, theoretical knowledge taught by teachers is actually assimilated by schoolchildren.  
**(Supporting sentence)**  
Undeniably, without compulsory homework assignments, school students tend not to revise what was taught the previous day. This would no doubt have a detrimental impact on their ability to memorise and put abstract ideas into practice.  
**(Example)**  
For example, in most developed countries such as America, Singapore and Russia, students are invariably encouraged to finish their homework exercises before attending school.  
**(Concluding thought)**  
The economic and educational superiority of these countries partly reflects the indispensability of homework in learning institutions.
</p>

Mặc dù những quan điểm trên, cá nhân tôi cho rằng nhờ vào những bài tập,
kiến thức lý thuyết được dạy bởi giáo viên thực sự được lĩnh hội bởi học sinh.
Không có những bài tập về nhà bắt buộc, học sinh thường không ôn lại những
gì được dạy ngày hôm trước. Điều này chắc chắn sẽ tác động tiêu cực lên khả
năng ghi nhớ và áp dụng những khái niệm trừu tượng. Ví dụ ở hầu hết các
nước phát triển như Mỹ, Singapore hay Nga, học sinh luôn được khuyến khích
hoàn thành bài tập về nhà trước khi đến trường. Sự phát triển về kinh tế và
giáo dục của những quốc gia này phần nào phản ánh sự thiết yếu của bài tập
về nhà.

- compulsory (adj) mandatory: bắt buộc
- review (t) revise: xem lại 
- remember = memorise (t) ghi nhớ
- abstract (adj) trừu tượng
- superiority (u) sự hơn hẳn
- indispensability u) necessity: sự thiết yếu

## Conclusion

Phần này đơn giản chúng ta cũng chỉ cần lặp lại ý kiến của một nhóm người khác cũng
như khẳng định lại quan điểm của bản thân. Tương tự những phần trước chúng ta cũng
có thể thêm phần “because” vào phía sau nếu viết đến đây cả bài vẫn chưa đủ 250 từ.

<p class="comment">
In conclusion, although many people argue that teachers should not set their students homework exercises because of the pressure they create, I firmly believe that the benefits they bring overshadow the disadvantages in the long run.
</p>

Tóm lại, mặc dù nhiều người cho rằng giáo viên không nên giao bài tập cho
học sinh bởi vì áp lực mà chúng tạo ra, tôi tin rằng những lợi ích chúng
mang lại sẽ lớn hơn những bất lợi trong dài hạn.

- outweigh (t) overshadow: lớn hơn, làm lu mờ
- in the long term (adv) in the long run: về lâu dài

## Full Essay

<p class="formula">
Some people believe that schoolchildren should not be given homework by their
teachers, whereas others argue that homework plays an important role in the
education of children. Discuss both of these views and give your own opinion.
</p>

<p class="comment">
**Today there are plenty of opposing opinions about whether** schoolchildren
should be given homework by their teachers. **Many people argue that**
assignments given to complete at home do not make a significant contribution
to the effectiveness of education. **I disagree with this point of view** and my
reasons are as follows.
</p>

<p class="comment">
**On the one hand, it is argued that** homework places an unneeded burden on
school pupils, who are already under too much pressure from learning at
school. **This argument highlights that**, unlike in past times, schoolchildren
nowadays must dedicate most of their daytime to attending school and
digesting a sheer volume of academic knowledge. **As a result**, if students are
compelled to study further at home, they will be deficient in time for
relaxation and recreational activities. **For this reason, those who oppose the setting of homework assignments believe that** this can eventually lead to
schoolchildren’s loss of motivation and interest in learning.
</p>

<p class="comment">
**In spite of the arguments mentioned above, I personally believe that** thanks
to exercises, theoretical knowledge taught by teachers is actually assimilated
by schoolchildren. Undeniably, without compulsory homework assignments,
school students tend not to revise what was taught the previous day. This
would no doubt have a detrimental impact on their ability to memorise and
put abstract ideas into practice. **For example**, in most developed countries
such as America, Singapore and Russia, students are invariably encouraged to
finish their homework exercises before attending school. The economic and
educational superiority of these countries partly **reflects** the indispensability
of homework.
</p>

<p class="comment">
**In conclusion, although many people argue that** teachers should not set their 
students homework exercises **because of** the pressure they create, **I firmly believe that** the benefits they bring overshadow the disadvantages in the
long run.
</p>

(290 words)


# OUTWEIGH

Đối với dạng câu hỏi ‘”Do the advantages outweigh the disadvantages” chúng ta cần trình bày khác một chút. Ví dụ câu hỏi của chúng ta đổi thành:

<p class="comment">
Some people think that employers should not care about the way their employees dress, because what matters is the quality of their work. Do the advantages of dress codes outweigh the disadvantages?
</p>

## Introduction

Đối với phần mở bài các câu Background information và People’s opinion chúng ta
vẫn viết bình thường. Tuy nhiên đến câu Your opinion chúng cần trả lời đúng câu hỏi
của đề bài đó là advantage có lớn hơn hơn disadvantage hay không.

Nếu chúng ta viết theo cách **“while I agree with the above viewpoint to some extent, I also believe that S + V”** thì mới chỉ đưa ra là vấn đề có cả hai mặt advantage và disadvantage nhưng chưa đưa ra được cái nào lớn hơn).

Vì vậy câu Your opinion chúng ta có thể đổi thành:

<p class="formula">
Although I partly agree with the above point of view, I believe that the benefits X brings outweigh/overshadow its disadvantages.
</p>

<p class="formula">
Although I partly agree with the above viewpoint, I believe X generate more benefits than disadvantages.
</p>

<p class="formula">
Although I partly agree with the above point of view, I believe that the disadvantages X creates bear no comparison with its benefits.  
</p>

Trường hợp chúng ta cho rằng disadvantage là lớn hơn thì chúng ta chỉ cần đổi lại vị trí của nó với benefits.

Trong cấu trúc này:

- outweigh = overshadow (t) lớn hơn, làm lu mờ
- bring no comparison with: không thể so với
- generate (t) tạo ra
- benefit = advantage (c) lợi ích
- disadvantage = drawback (c) bất lợi

Khi viết như thế này chúng ta vừa thể hiện được mình công nhận là vấn đề này có cả benefits và drawbacks/disadvantages, vừa nhận xét được cái nào lớn hơn.

Ví dụ trong trường hợp này X chính là dress codes. Như vậy chúng ta có thể viết được
một câu để đưa ra ý kiến của mình như sau:

<p class="comment">
Although I partly agree with the above point of view, I believe that the benefits dress codes bring overshadow their disadvantages.
</p>

<p class="comment">
Although I partly agree with the above point of view, I believe that the disadvantages dress codes create bear no comparison with their benefits.
</p>

<p class="comment">
Although I partly agree with the above point of view, I believe dress codes generate more benefits than disadvantages.
</p>


Áp dụng tương tự chúng ta có thể viết một phần introduction như sau:

**(Background information)**  
Today there are plenty of opposing opinions about whether organisations should have mandatory dress codes or not. 
**(People’s opinion)**  
Many people argue that these rules should not be considered crucial in modern working environment.  
**(Your opinion)**  
Although I partly agree with the above point of view, I believe that dress codes generate more benefits than disadvantages.

## Body

Hai phần thân bài không có gì khác so với hai câu hỏi còn lại. Cũng đều là hai đoạn ý
kiến của mình:

<ul class="formula">
<li>On the one hand,</li>
<li>On the other hand, I also claim that</li>
</ul>

## Conclusion

Đối với phần kết bài đơn giản chúng ta có thể paraphrase lại câu opinion ở phần mở bài như sau:

<p class="formula">
In conclusion, while I acknowledge some drawbacks of N/$V_ing$, it is my opinion that S + V
</p>

Để viết nhanh S + V lúc này các bạn hãy dùng vế sau của câu your opinion của phần introduction như đã gợi ý ở trên mà các bạn chưa dùng.

Ví dụ:

<p class="comment">
In conclusion, while I acknowledge some drawbacks of dress codes, it is my
opinion that the disadvantages they create bear no comparison with
advantages.
</p>

## Full Essay

<p class="formula">
The use of social media is replacing face-to-face interaction among many people in
society. Do you think the advantages outweigh the disadvantages?
</p>

<p class="comment">
It is true that face-to-face communication today is gradually being superseded by
online conversations on social media sites such as Facebook or Twitter. Many hold
the view that this disposition has a detrimental impact on frequent users. While I
partly agree with this point of view, I believe that they generate more benefits for
society than disadvantages.
</p>

<p class="comment">
On the one hand, the overuse of social media diminishes the quality of interpersonal
communication. Admittedly, a great many people are obsessed with social networks
that they invariably stare at their smartphone screen without paying attention to
those around them. This routine is likely to lead them to become indifferent to
real-life conversations and simultaneously direct their attention to strangers in a
virtual world. For example, in the old days, people dedicated most of their leisure
time to meeting up and chatting with one another; however, nowadays in meetings,
dates or group work sessions, people often interact more on social networks than
with others. This indicates that personal relationships could become more distant
due to social media.
</p>

<p class="comment">
Despite the above-mentioned downsides, I claim that social media make many daily
tasks swifter, more convenient and cost-effective than before. Needless to say, a
wide range of human activities are contingent on these platforms from everyday
communication to the exchange of information in the workplace. For example, social
networking sites are a powerful marketing tool allowing enterprises to exhibit their
product information and promote them to potential clients. This approach makes it
possible for these organisations to save a great deal of time and budget compared to
other conventional marketing strategies in newspapers or on television, which
shows that social media can offer enormous benefits if used properly.
</p>

<p class="comment">
According to the facts outlined above, while I acknowledge some drawbacks of social
networks, I believe that these disadvantages bear no comparison with benefits they
bring to society.
</p>

(308 words)

- social media (u/plural) social media site, social network, social networking site: mạng xã hội 
- face-to-face (adj) direct: trực tiếp
- replace = supersede (t) thay thế
- conversation (c) cuộc trò chuyện
- frequent user = heavy user (c) người dùng nhiều, thường xuyên
- overuse (u) excessive use: sự dùng quá nhiều, lạm dụng
- diminish (i/t) reduce, decrease: (làm) giảm
- interpersonal (adj) giữa các cá nhân
- be obsessed with = be addicted to sth: nghiện cái gì 
- invariably (adv) luôn luôn, lúc nào cũng
- stare at: nhìn chằm chằm
- pay attention to = take notice of: chú ý đến
- dedicate/devote sth to sth/doing sth: dành cái gì cho cái gì hoặc để làm gì 
- each other = one another
- date (c) buổi hẹn hò
- group work session (c) buổi làm việc nhóm
- interact (i) tương tác
- indifferent (to) (adj) unconcerned: không quan tâm, thờ ơ
- simultaneously (adv) đồng thời 
- help/enable sb to do sth: giúp/làm cho ai có thể làm gì đó
- daily (adj) everyday: hằng ngày
- quick = rapid = swift = prompt (adj) nhanh
- convenient (adj) thuận tiện
- economical (adj) cost-effective: tiết kiệm
- be contingent/dependent/reliant on: phụthuộc vào
- platform (c) nền tảng
- exchange (s) sự trao đổi 
- strong (adj) powerful: mạnh mẽ
- show = display = exhibit (t) phô ra, trưngbày
- product information (u) thông tin sản phẩm
- advertise = promote = market (t) quảngcáo
- potential (adj) tiềm năng
- budget (c) ngân sách
- compared to (phr) so với 
- conventional (adj) traditional: truyền thống

# CAUSE & CONSEQUENCE

Đây là dạng câu hỏi về “nguyên nhân”, “hậu quả” hoặc là đòi hỏi bạn cần đưa ra “giải
pháp”. Câu hỏi có thể chứa một, hai hoặc cả ba ý này.

Ví dụ:

<p class="comment">
The dangers of smoking are well-known, yet many people continue with this habit. What are the causes of this? How can we reduce smoking in society?
</p>

<p class="comment">
Obesity (being extremely overweight) is a growing problem in society. What are the causes and effects of this, and make suggestions to deal with this problem.
</p>

Trong đề bài thứ nhất “What are the causes of this?” chính là hỏi về nguyên nhân, và
“How can we reduce smoking in society?” là yêu cầu bạn đưa ra giải pháp.

Trong đề bài thứ hai “What are the causes and effects of this?” chính là hỏi về
nguyên nhân và tác động, trong khi đó “make suggestions to deal with this problem”
là yêu cầu bạn đưa ra giải pháp.

Ngoài ra cần lưu ý là ngoài những câu hỏi trên, đôi khi đề bài cũng chứa một câu hỏi
yêu cầu chúng ta tìm ra: “difficulties/differences/factors/changes/qualities (…)”

Ví dụ:

<p class="comment">Happiness is considered very important in life. Why is it difficult to define? What factors are important in achieving happiness?</p>
<p class="comment">More and more people are migrating to cities in search of a better life, but city life can be extremely difficult. Explain some of the difficulties of living in a city?</p>
<p class="comment">Many people are optimistic about the 21st century and expect scientists to make positive changes to the world. What changes would you like to see in the new century?</p>
<p class="comment">We can get knowledge from news, but some people think we cannot trust journalists. What qualities do you think a successful journalist should have?</p>
<p class="comment">The advance of science and technology has a significant impact on people, but the role of artists is also important, such as musicians, painters and writers. What can the arts tell us about life that science cannot?</p>
<p class="comment">What are the differences between traditional food and fast food?</p>
<p class="comment">It is generally believed that education is of vital importance to individual development and the well-being of societies. What should education consist of to fulfil both these functions?</p>

Một số từ đề bài hay dùng để hỏi các ý trên:

Nguyên nhân: 

* reason
* cause
* contributing factor
* driver
* driving force
* source
* origin 

Tác động/hậu quả: 

* effect
* consequence
* implication
* result
* repercussion 

Giải pháp: 

* solution
* suggestion
* method
* possible ways
* strategy
* advice
* remedy

Khó khăn/bất lợi: 

* difficulty
* problem
* drawback
* disadvantage

Đặc điểm chung của những câu hỏi ở dạng này đó là chúng ta đơn giản sẽ trả lời trực
tiếp những câu hỏi đề bài đưa ra.

Example 1

<p class="formula">
Obesity (being extremely overweight) is a growing problem in society.
What are the causes and effects of this, and make suggestions to deal with this
problem.
</p>

Béo phì (sự thừa cân quá mức) đang ngày càng trở thành một vấn đề của xã hội.
Đâu là nguyên nhân và tác động của nó, hãy đưa ra một vài gợi ý để giải quyết vấn đề
này.

- obesity (u) béo phì                       
- growing (adj) increasing: ngày càng
- overweight (adj) fat: thừa cân

## Introduction

### Background Information

Đối với dạng này phần mở bài sẽ không viết giống các phần trước vì đề bài không hỏi
ý kiến của chúng ta. Tuy nhiên chúng ta vẫn cần viết một câu “Background
information”. Để viết nhanh chúng ta hãy dựa vào đề bài.

Ví dụ câu cho bởi đề bài: “obesity (being extremely overweight) is a growing problem
in society”

Chúng ta chỉ cần viết lại một câu với ý nghĩa tương tự để nêu ra vấn đề chúng ta sẽ
thảo luận:

<p class="comment">
(Background information) It is well acknowledged that obesity has gradually become a threat to people’s health at any age, especially in the developed world.
</p>

Ngày nay béo phì đang dần trở thành mối đe dọa tới sức khỏe con người ở bất kỳ độ tuổi nào, đặc biệt là ở các nước phát triển.

Sau khi viết xong câu đầu đối với dạng này chúng ta thường luôn có thể thêm một câu mục đích (the purpose) của bài viết.

Chúng ta có thể bắt đầu câu này bằng:

<ul class="formula">
<li>Here I will</li>
<li>It is certainly necessary to $V_o$</li>
<li>It is clearly important to $V_o$</li>
<li>It is worthwhile to $V_o$</li>
<li>It is reasonable to $V_o$</li>
</ul>

Sau đó tùy vào câu hỏi của đề bài, nếu đề bài hỏi về “cause/effect” chúng ta
có thể viết tiếp như sau:

<p class="comment">Here I will discuss the causes and effects of being extremely overweight.</p>

Hoặc:

<p class="comment">It is important to discuss the causes and effects of being extremely</p>
overweight.

Nếu hỏi thêm về ý “solution” chúng ta có thể viết tiếp câu trên, sử dụng:

<p class="comment">Here I will discuss the causes, effects of being extremely overweight as well</p>
as providing suggestions to deal with/address/tackle this problem.

Hoặc:

<p class="comment">It is important to discuss the causes and effects of being extremely</p>
overweight as well as providing suggestions to deal with/address/tackle this
problem.

- It is certainly important/necessary/worthwhile to
- Here I will
+ discuss the reasons for/the causes of/the driver behind
+ analyse the consequences/effects of
+ provide suggestions (or methods) to address/tackle/deal with this problem
+ examine the drawbacks of

Trong trường hợp này đề bài hỏi về cả ba ý cause/effect/solution nên chúng ta có thể
viết một phần introduction như sau:

<p class="comment">
(The purpose) It is certainly important to discuss the causes, effects of being extremely overweight as well as providing suggestions to deal with this problem.
</p>

Như vậy chúng ta có một câu nói về mục đích của bài viết chứa đầy đủ những yêu
cầu của đề bài.

Và chúng ta có một phần introduction đầy đủ như sau:

<p class="comment">
It is well acknowledged that obesity has gradually become a threat to human
health at any age, especially in the developed world. Therefore, It is certainly
important to discuss the causes, effects of being extremely overweight as well
as providing suggestions to deal with this problem.
</p>

Ngoài ra còn rất nhiều cách để chúng ta viết câu mục đích ví dụ như:

<p class="comment">The objective of this essay is to outline both the source of X and appropriate ways to deal with it.</p>
<p class="comment">It is the goal of this essay to outline the potential causes of this problem and suggest possible solutions to address it.</p>
<p class="comment">The objective of this essay is to evaluate the forces behind this trend and its consequences.</p>
<p class="comment">This essay will present an overall view of the causes and potential solutions.</p>
<p class="comment">The potential effects of such a trend will be discussed in detail below, followed by suggested solutions.</p>
<p class="comment">Below is an outline of some differences between A and B.</p>

## Body

Phần này chúng ta đơn giản cũng thường dùng mỗi đoạn để trả lời theo thứ tự của
các yêu cầu.

Đoạn 1 chúng ta có thể viết về cause, đoạn body 2 sẽ về effect. Cách tổ chức một
đoạn thân bài cũng vẫn như bình thường gồm 4 phần:

Topic sentence -> Supporting sentence -> Example/More explanation ->
Concluding thought.

Thông thường đề bài sẽ chỉ hỏi hai trong ba phần “cause - effect - solution”. Việc này
sẽ giúp chúng ta dễ trình bày hai đoạn thân bài như bình thường hơn.
Tuy nhiên trong trường hợp này để các bạn có sự hình dung về cách viết cho từng
dạng rõ hơn nên đề bài bao gồm cả ba phần.

Thông thường giữa mỗi đoạn thân bài với nhau sẽ không có các quan hệ tương đồng
hoặc tương phản như các dạng trước nên chúng ta cũng không cần dùng các từ nối
như “however, on the other hand…”.

Tùy vào câu hỏi câu topic của mỗi đoạn thân bài chúng ta có thể bắt đầu bằng:

Nêu ra nguyên nhân, tác động, khó khăn (…):


<ul class="formula">
<li>The main (hoặc principal/major/primary) cause is that S + V</li>
<li>The most common factor responsible for N/$V_ing$ is N (hoặc that S+V)</li>
<li>N/$V_ing$ is the most common factor that play a big role in N/$V_ing$</li>
<li>N/$V_ing$ is widely recognized as the determining factor.</li>
<li>N/$V_ing$ is attributed to N/$V_ing$</li>
<li>One of the major drawbacks of N/$V_ing$ is N (hoặc that S + V)</li>
<li>The main (hoặc principal/major/primary) effect of N/$V_ing$ is N (hoặc that S + V)</li>
<li>One of the most significant benefits obtained from X is N (hoặc that S + V)</li>
<li>Turning to possible effects, S + V</li>
</ul>

Đưa ra giải pháp:

<ul class="formula">
<li>The best approach to address ... is simply to + $V_o$</li>
<li>The best way to Vo is to + $V_o$</li>
<li>This problem can be solved by $V_ing$</li>
<li>Moving on to possible solutions, S + V </li>
</ul>

Lưu ý điểm đặc biệt của dạng này đó là các từ đề cập đến “causes” “effects” hay
“solutions”… thường là số nhiều. Vì vậy đoạn của chúng ta có thể đưa ra một hoặc
nhiều hơn một nguyên nhân, tác động… chính trong một đoạn.

Trong trường hợp đoạn thân bài chúng ta có nhiều hơn một ý chính. Như đã hướng
dẫn ở các phần trước chúng ta có thể dùng các từ sau để bắt đấu ý thứ hai:

<ul class="formula">
In addition,      
Additionally,     
Besides,          
Furthermore,      
Moreover,         
Another reason for this is N (hoặc that S + V)            
Another force that drives N/$V_ing$ is + N (hoặc that S + V)
The second consequence of N/$V_ing$ is N (hoặc that S+ V)
The second noteworthy problem of N/$V_ing$ is N (hoặc that S + V)
</ul>

Hãy quan sát đoạn thân bài hoàn chỉnh dưới đây:

<p class="comment">
**(Topic sentence)**  
One of the principal factors responsible for causing a normal weight person to be obese is an unbalanced diet.   
**(Supporting sentence)**  
In simpler terms, the excessive consumption of food products which are high in calories will inevitably lead to the state of being overweight.   
**(More explanation)**  
Due to its convenience, various types of fast food, however, are currently popular with numerous people, although these foodstuffs in fact provide very little nutrition and contain large amounts of unhealthy fats.  
**(Concluding thought)**  
As a consequence, it is not surprising that such an unscientific eating habit renders many extremely overweight.  
</p>

<p class="comment">
**(Topic sentence)**  
Undoubtedly, obesity can trigger many health-related issues involving both physical and psychological ailments.  
**(Supporting sentence 1 + Example 1)**  
Studies have shown that it is the origin of various complications such as diabetes, which leads to millions of fatalities per year all over the world.  
**(Supporting sentence 2)**  
Furthermore, the possession of an oversize shape could lead an ordinary person to undergo an inferiority complex or even deep depression.   
**(Example 2)**  
For example, female pupils at an impressionable age are likely to feel excluded and some might even have the intention of committing suicide if they are repeatedly teased by wicked classmates because of their sizeable and bulky physique. All these facts demostrate the detrimrntal effect of being overweight on people’s welfare.  
</p>

<p class="comment">
**(Topic sentence)**  
The best solution to this issue might be to incorporate lessons regarding scientific and reasonable eating in the school curriculum.  
**(Supporting sentence)**  
Educational institutes are where young pupils dedicate their early years to acquiring what will have an immense impact on their behaviour and living habits later on.   
**(Example)**  
For example, through the provision of nutritionally balanced lunches, schools can help susceptible young schoolchildren gradually develop good eating routines after returning home.  
**(Concluding thought)**  
As a result, they may become more selective when it comes to the intake of high-calorie foodstuffs.
</p>


Yếu tố chính làm cho một người có căn nặng bình thường trở nên béo phì là
một chế độ ăn thiếu cân bằng.   Việc tiêu thụ quá nhiều các thực phẩm có hàm
lượng calorie cao trong một thời gian dài sẽ tất yếu dẫn đến sự thừa cân.   Tuy
nhiên nhiều loại thức ăn nhanh hiện nay đang được ưa chuộng bởi rất nhiều
người bởi vì sự tiện lợi của nó, mặc dù thực tế những thực phẩm này cung cấp
rất ít chất dinh dưỡng và chứa lượng lớn chất béo.   Vì vậy không ngạc nhiên là
thói quen ăn uống thiếu lành mạnh này làm cho nhiều người trở nên béo phì.  

Béo phì có thể gây ra nhiều vấn đề liên quan đến sức khỏe bao gồm cả các căn
bệnh về thể chất và tâm lý.   Nó là nguồn gốc của rất nhiều những biến chứng
nguy hiểm khác ví dụ như bệnh tiểu đường, căn bênh dẫn đến cái chết của
hàng triệu người mỗi năm trên khắp thế giới.   Ngoài ra việc sở hữu một thân
hình quá khổ có thể làm cho một người mình thường trải qua cảm giác tự ti
mặc cảm hay thậm chí là trầm cảm.   Ví dụ như học sinh nữ trong độ tuổi dễ bị
tác động có thể cảm thấy bị loại trừ và một số thậm chí có ý định tự tử nếu
liên tục bị trêu chọc bởi bạn cùng lớp vì thân quá cỡ của mình.   Tất cả những
thực tế này chứng minh tác động gây hại của béo phì đối với sự khỏe mạnh và
hạnh phúc của mọi người.  

Biện pháp tốt nhất có thể là đưa các bài học liên quan đến việc ăn uống một
cách khoa học và hợp lý vào trong chương trình giảng dạy của nhà trường.  
Trường học là nơi trẻ em dành những năm đầu đời của mình để học những
thứ có ảnh hưởng rất lớn đến các hành vi và thói quen sinh hoạt của chúng
sau này.   Thông qua việc cung cấp những bữa trưa cân bằng về dinh dưỡng,
trường học có thể giúp học sinh từ từ phát triển những thói quen ăn uống
lành mạnh sau khi trở về nhà và có chọn lọn hơn khi ăn những thực phẩm giàu
calorie.  

- unbalanced (adj) thiếu cân bằng
- obese (adj) béo phì
- excessive (adj) immoderate: thái quá, quá độ
- consumption (u) sự tiêu thụ
- foodstuff (c) food product: thực phẩm
- be high in something: có hàm lượng cái gì đó cao
- calorie (c) đơn vị năng lượng
- inevitably (adv) unavoidably: tất yếu, không thể tránh khỏi.
- numerous = many
- nutrition (u) nutriment, nutrient, nourishment: chất dinh dưỡng
- render (t) cause: làm cho
- health-related (adj) liên quan đến sức khỏe
- disease (c) sickness, illness, ailment: bệnh
- source (c) origin: nguồn gốc
- complication (c) (y học) biến chứng
- dangerous (adj) hazardous: nguy hiểm
- diabetes (u) bệnh tiểu đường
- lead to (v) result in: dẫn đến
- oversize (adj) quá khổ
- inferiority complex (c) mặc cảm tự ti
- depression (u) trầm cảm
- related to/relating to/connected with/linked to/with/associated with (+n): liên quan đến
- about = regarding = concerning = as to (pre) về cái gì đó
- impressionable = susceptible (adj) dễ bị tác động
- commit suicide: tự tử
- wicked (adj) xấu
- sizable (adj) to, lớn
- bulky (adj) cồng kềnh
- tease = mock (t) trêu chọc
- physique = shape = figure (c) vóc dáng
- include (sth in sth) (t) incorporate: bao gồm vào
- curriculum (c) chưng trình học
- school = educational centre = learning institute (c) trường học, cơ sở giáo dục
- early years (n) những năm đầu đời
- nutritionally balanced (adj) cân bằng về mặt dinh dưỡng
- selective (adj) có chọn lọc

## Conclusion

Ở phần kết bài chúng ta cũng viết một cách đơn giản và tóm lại các ý chính đã đề cập
sử dụng ngôn ngữ khác đi một chút như ví dụ dưới đây:

<p class="comment">In conclusion, while obesity can result in severe health effects, raising people’s awareness of a healthy diet can be an effective measure to tackle it.</p>

Kết luận, mặc dù bệnh béo phì có thể dẫn đến những tác động nghiêm trọng
cho sức khỏe, việc nâng cao nhận thức của mọi người về tầm quan trọng của
một chế độ ăn uống có thể là một cách hiệu quả để giải quyết vấn đề này.

- health effect (c) ảnh hưởng lên sức khỏe   
- awareness (u) nhận thức

## Full Essay

<p class="formula">
Obesity (being extremely overweight) is a growing problem in society.
What are the causes and effects of this, and make suggestions to deal with this
problem.
</p>

<p class="comment">
It is well acknowledged that obesity has gradually become a threat to human
health at any age, especially in the developed world. Therefore, It is certainly
important to discuss the causes, effects of being extremely overweight as
well as providing suggestions to deal with this problem.
</p>

<p class="comment">
One of the principal factors responsible for causing a normal weight person
to be obese is an unbalanced diet. In simpler terms, the excessive
consumption of food products which are high in calories will inevitably lead to
the state of being overweight. Due to its convenience, various types of fast
food, however, are currently popular with numerous people, although these
foodstuffs in fact provide very little nutrition and contain large amounts of
unhealthy fats. As a consequence, it is not surprising that such an unscientific
eating habit renders many extremely overweight.
</p>

<p class="comment">
Undoubtedly, obesity can trigger many health-related issues involving both
physical and psychological ailments. Studies have shown that it is the origin of
various complications such as diabetes, which leads to millions of fatalities per
year all over the world. Furthermore, the possession of an oversize shape
could lead an ordinary person to undergo an inferiority complex or even deep
depression. For example, female pupils at an impressionable age are likely to
feel excluded and some might even have the intention of committing suicide if
they are repeatedly teased by wicked classmates because of their sizeable and
bulky physique.
</p>

<p class="comment">
The best solution to this issue might be to incorporate lessons regarding
scientific and reasonable eating in the school curriculum. Educational
institutes are where young pupils dedicate their early years to acquiring what
will have an immense impact on their behaviour and living habits later on. For
example, through the provision of nutritionally balanced lunches, schools can
help susceptible young schoolchildren gradually develop good eating routines
after returning home and be more selective when it comes to the intake of
high-calorie foodstuffs.
</p>

<p class="comment">
In conclusion, while obesity can result in severe health effects, raising
people’s awareness of a healthy diet can be an effective measure to tackle it.
</p>

(343 words)

# MIXED QUESTIONS

Dạng mix là dạng vừa hỏi về ý kiến cá nhân, vừa hỏi một câu về cause/effect/solution.
Cả hai dạng này chúng ta đều đã phân tích cách viết ở các phần trước.

Example:

<p class="comment">Some parents buy their children whatever they ask for, and allow their children to do whatever they want. Is this a good way to raise children? What consequences could this style of parenting have for children as they get older?
</p>

<p class="comment">These days more fathers stay at home and take care of their children while mothers go out to work. What could be the reasons for this? Do you think it is a positive or negative development?
</p>

<p class="comment">As most people spend a major part of adult life at the place of work, job satisfaction is an important part of individual well-being. What are the factors that contribute to job satisfaction? Are all the expectations for job satisfaction realistic?
</p>

<p class="comment">Some people think that old buildings should be knocked down and give way to new buildings. Do you agree or disagree? Why some people claim that they are important?
</p>

Trong các câu hỏi trên các bạn sẽ thấy một điểm chung là chúng vừa chứa một câu
hỏi về ý kiến cá nhân và một câu hỏi thuộc dạng cause/consequence/solution.

Bây giờ hãy quan sát ví dụ dưới đây:

Example 1

<p class="formula">
Some parents buy their children whatever they ask for, and allow their children to
do whatever they want. Is this a good way to raise children? What consequences
could this style of parenting have for children as they get older?
</p>

Một số cha mẹ mua cho con cái họ bất cứ cái gì chúng đòi, và cho phép chúng làm
bất cứ cái gì chúng muốn. Đây có phải là một cách tốt để nuôi dạy con không? Đâu
là những hậu quả mà cách nuôi dạy con này gây ra cho những đứa trẻ khi chúng
trưởng thành?

- ask for: đòi, xin
- raise (t) rear, bring up, nurture: nuôi nấng
- parenting (u) upbringing, raising: sự nuôi dạy

## Introduction

Nhìn vào câu hỏi chính ta sẽ thấy chúng bao gồm hai phần khác nhau. Phần thứ nhất
là ‘is this a good way to raise children?” chính là câu hỏi thuộc dạng hỏi ý kiến cá
nhân của người viết và được tự do chọn hướng trả lời. Tuy nhiên đối với đa số người
học IELTS không phải là bản xứ chúng ta chỉ nên chọn một hướng để thân bài chỉ có
một đoạn nói về ý kiến. Nếu phải viết cả hai đoạn thân bài cho phần ý kiến này và
một đoạn cho phần sau, đa số các bạn sẽ không thể viết kịp trong chỉ 40 phút.

Câu hỏi tiếp theo bắt đầu là “what consequences” chính là thuộc dạng
cause/effect/solution vừa mới xét ở phần trước (hãy coi lại câu “the purpose” của
dạng này ở phần trước)

Như đã thảo luận ở các phần trước, câu hỏi đầu tiên chúng ta có thể trình bày phần
mở bài bao gồm:
Background information => People’s opinion => Your opinion

Trong khi đó dạng cause/effect/solution chúng ta có thể trình bày phần mở bài như
sau:
Background information => The purpose

Như vậy gộp lại thì thông thường phần mở bài của dạng này chúng ta có thể trình
bày như sau:

Background information => People’s opinion => Your opinion + The purpose

Các bạn có thể viết theo các cách khác tuy nhiên dù viết theo cách nào chúng ta cũng
nên bao gồm Your opinion và The purpose để trả lời cho yêu cầu của đề bài.

Ví dụ:

It is true that nowadays people have opposing ideas about whether parents should satisfy all their children’s requirements or not. Some individuals hold the viewpoint that it is a good style of parenting. I completely disagree with this point of view and it is necessary to analyse the negative effects of such a short-sighted mentality.

## Body

Đối với phần thân bài chúng ta sẽ dành một đoạn để viết về ý kiến của mình.
Đối với đoạn thân bài còn lại chúng ta tương tự sẽ trả lời yêu cầu thứ hai của đề bài
giống như phần trước.

Ở đây chúng ta sẽ thấy là hai đoạn thân bài không có những mối quan hệ tương đồng
và tương phản. Hai phần này sẽ thường tách rời nhau.

**(Topic sentence)**   
The main reason to oppose overindulgence is that it will negatively affect children’s personality.  
**(Supporting sentence)**   
Being overly indulged generally turn initially well-behaved children into those having difficulty in developing self-regulation. In simpler term, whenever these youngsters become excessively demanding but are turned down, they have a predisposition towards misconduct, or even show disrespect to their own parents.  
**(Example)**   
For example, many surveys have shown that such children are more likely to become black sheep in class, have low academic performance, drink alcoholic beverages, and get into a struggle.  
**(Concluding thought)**   
This shows that it is not advisable to spoil children by fulfilling all their demands.

**(Topic sentence)**   
Turning to possible repercussions, permissive parents’ children are inclined to become adults who merely show consideration for themselves and belittle the needs and emotions of others.  
**(Supporting sentence)**   
Such a personality trait is a huge barrier to integration into later working environments which invariably require individuals to adapt themselves to their organizational cultures.  
**(More explanation)**  
These self-fish adults will hardly ever sacrifice themselves for collective benefits, and often just demand others’ assistance but never be willing to do the reverse.  
**(Concluding thought)**   
Consequently, there are not many people who can endure such a bad temperament and the majority will choose to distance themselves from this self-centered person.  


Lý do chính tôi cho rằng cha mẹ không nên nuông chiều con cái của họ đó là sự
nuông chiều quá mức sẽ tác động rất tiêu cực lên tính cách của con cái họ.
Được nuông chiều quá mức thường làm cho những đứa trẻ ngoan ngoãn lúc
đầu gặp khó khăn trong việc phát triển khả năng kiểm soát bản thân. Bất cứ khi
nào những đứa trẻ này đòi hỏi quá mức nhưng bị từ chối, chúng sẽ có khuynh
hướng cư xử không đúng mực, thậm chí thiếu tôn trọng chính cha mẹ của
chúng. Ví dụ như nhiều cuộc khảo sát đã chỉ ra rằng những đứa trẻ như vậy có
nhiều khả năng trở thành những thành phần cá biệt ở lớp, có kết quả học tập
thấp, uống rượu bia và đánh nhau hơn. Điều này cho thấy rằng làm hư con cái
băng việc thỏa mãn tất cả yêu cầu của chúng là thiếu khôn ngoan.

Hậu quả đó là con cái của những những bậc cha mẹ dễ dãi có khuynh hướng
trở thành những người chỉ quan tâm đến bản thân và xem nhẹ nhu cầu cũng
như cảm xúc của những người khác. Đặc điểm tính cách này là một rào cản rất
lớn đối với việc hòa nhập vào môi trường làm việc sau này, nơi luôn đòi hỏi bất
cứ cá nhân nào cũng phải thay đổi bản thân để trở nên phù hợp với văn hóa
của tổ chức. Những người ích kỷ này sẽ hiếm khi hi sinh cá nhân mình cho lợi
ích tập thể và thường chỉ đòi hỏi sự giúp đỡ của người khác nhưng thường
không bao giờ sẵn lòng làm điều ngược lại. Kết quả, không có nhiều người có
thể chịu đựng được tính cách xấu như vậy và đa số sẽ chọn xa lánh những cá
nhân tự cho mình là trung tâm này.

- indulge (t) overindulge: nuông chiều
- overindulgence (u) sự nuông chiều quá mức
- initially (adv) originally, at the beginning: lúc đầu
- obedient (adj) well-behaved: ngoan ngoãn, biết nghe lời, cư xử đúng mực
- self-control = self-regulation (u) khả năng kiểm soát bản thân
- overly (adv) too, excessively: quá mức
- demanding (adj) đòi hỏi
- refuse (t) turn down: từ chối
- misconduct = bad behaviour (u) misbehaviour: cư xử không đúng mực
- disrespect (s/u) sự thiếu tôn trọng
- black sheep (n) thành phần cá biệt
- academic performance (u) learning outcome: thành tích học tập
- alcoholic beverage (c) thức uống có cồn
- get into a fight/struggle (phr) đánh nhau
- permissive (adj) lenient: dễ dãi, khoan dung
- be inclined to do sth: có khuynh hướng
- show consideration for: quan tâm, chú ý đến người khác
- belittle (t) undervalue: coi thường, xem nhẹ
- character trait = personality trait (c) đặc điểm tính cách
- a barrier to: một rào cản đối với
- integration (into) (u) sự hòa nhập
- require (sb to do sth) (t) demand: đòi hỏi
- organizational culture (c) văn hóa tổ chức
- sacrifice (t) hy sinh
- collective benefit (c) lợi ích tập thể
- be willing to do sth: sẵn lòng làm gì
- the reverse = the opposite = the converse: điều ngược lại
- endure (t) bear, tolerate: chịu đựng
- temper (n) temperament, disposition: tính khí, tâm tính
- keep away from sb = distance oneself from sb: xa lánh, giữ khoảng cách với ai đó

## Conclusion

Đối với kết luận chúng ta có thể đơn giản khẳng định lại ý kiến cá nhân của mình.

<p class="comment">In conclusion, although many people consider indulgence a workable
parenting method, I believe that strict upbringing is of vital importance
because it helps kids develop self-regulation and respect for others.</p>

Tóm lại, mặc dù nhiều người xem sự nuông chiều là một phương pháp nuôi
dạy con hiệu quả, tôi tin rằng việc nuôi dạy nghiêm khắc là rất quan trọng vì
nó giúp trẻ em phát triển khả năng tự chủ và sự tôn trọng người khác.

- strict = rigid (adj) nghiêm khắc

## Full Essay

<p class="formula">Some parents buy their children whatever they ask for, and allow their children to do whatever they want. Is this a good way to raise children? What consequences could this style of parenting have for children as they get older?
</p>

<p class="comment">
It is true that nowadays people have opposing ideas about whether parents
should satisfy all their children’s requirements or not. Some individuals hold
the viewpoint that it is a good style of parenting. I completely disagree with
this point of view and it is necessary to analyse the negative effects of such a
short-sighted mentality.
</p>

<p class="comment">
One main reason to oppose overindulgence is that it will negatively affect
children’s personality. Being overly indulged generally turns initially
well-behaved children into those having difficulty in developing
self-regulation. In simpler term, whenever these youngsters become
excessively demanding but are turned down, they have a predisposition
towards misconduct, or even show disrespect to their own parents. For
example, many surveys have shown that such children are more likely to
become black sheep in class, have low academic performance, drink alcoholic
beverages, and get into a struggle. This shows that it is not advisable to spoil
children by fulfilling all their demands.
</p>

<p class="comment">
Turning to possible repercussions, permissive parents’ children are inclined to
become adults who merely show consideration for themselves and belittle the
needs and emotions of others. Such a personality trait is a huge barrier to
integration into later working environments which invariably require
individuals to adapt themselves to their organizational cultures. These self-fish
adults will hardly ever sacrifice themselves for collective benefits, and often
just demand others’ assistance but never be willing to do the reverse.
Consequently, there are not many people who can endure such a bad
temperament and the majority will choose to distance themselves from this
self-centered person.
</p>

<p class="comment">
In conclusion, although many people consider indulgence a workable
parenting method, I believe that strict upbringing is really necessary because
it helps kids develop self-regulation and respect for others.
</p>

(292 words)